"""Payment providers.

One subpackage per provider. Each one carries the provider's full API —
generated from their OpenAPI specification, checked in, and regenerated by a
script rather than edited — plus the pieces the specification leaves out:
webhook verification, the environments, and whatever the provider documents
in prose instead of in the schema.

Available:

- **`openpix`** — OpenPix / Woovi (Pix). 358 schemas, 105 operations,
  webhook signature verification, and exact-cents helpers.

.. code-block:: python

    from tempest_fastapi_sdk import HTTPClient
    from tempest_fastapi_sdk.integrations.payment.openpix import (
        OpenPixClient,
        OpenPixEnvironment,
    )

    http: HTTPClient = HTTPClient(
        base_url=OpenPixEnvironment.SANDBOX.base_url,
        default_headers={"Authorization": "<your AppID>"},
    )
    client: OpenPixClient = OpenPixClient(http)

Importing a provider costs almost nothing: its generated schemas load on
first use, not on import.
"""

from tempest_fastapi_sdk.integrations.payment import openpix as openpix

__all__: list[str] = ["openpix"]
