"""Messaging providers.

One subpackage per provider, carrying its full API — generated from the
provider's OpenAPI specification, checked in, and regenerated by a script
rather than edited — plus whatever the specification leaves out.

Available:

- **`zap`** — the in-house WhatsApp gateway. 20 schemas, 18 operations, a
  typed client over :class:`~tempest_fastapi_sdk.utils.HTTPClient`.

.. code-block:: python

    from tempest_fastapi_sdk import HTTPClient
    from tempest_fastapi_sdk.integrations.messaging.zap import (
        SendTextRequest,
        ZapClient,
    )

    http: HTTPClient = HTTPClient(
        base_url="http://127.0.0.1:3000",
        default_headers={"x-api-key": "<your key>"},
    )
    client: ZapClient = ZapClient(http)
    accepted = await client.send_text(
        body=SendTextRequest(to="5511999999999", text="oi"),
        idempotency_key="4f1c…",
    )

!!! warning "A send is not a delivery"
    Every send answers ``202`` with the row it enqueued, not with a
    confirmation that WhatsApp has the message. What happened afterwards
    arrives on the gateway's status webhook, and **that webhook has no
    schema in the specification yet** — so this package does not model it.
    A service that needs delivery state reads it from the webhook itself
    for now.

Importing a provider costs almost nothing: its generated schemas load on
first use, not on import.
"""

from tempest_fastapi_sdk.integrations.messaging import zap as zap

__all__: list[str] = ["zap"]
