"""Factories for the per-domain 404 / 409 exceptions every project writes.

Declaring an identifiable ``NOT_FOUND`` for one aggregate is thirty lines
that differ from the next aggregate's by three strings — and the shape is
not guessable. :class:`~tempest_fastapi_sdk.db.BaseRepository` raises the
class it was given as ``exception_class(message=...)``, so the obvious
constructor — the one taking the id, because the id is what the *caller*
holds — turns every repository miss into a ``TypeError``: a 500 where a
404 belongs, with nothing pointing at the cause.

:func:`not_found_exception` and :func:`conflict_exception` build classes
that accept both call shapes, so neither the caller nor the repository
has to know about the other::

    BudgetNotFoundException = not_found_exception(
        "BUDGET_NOT_FOUND",
        subject="Orcamento",
        field="budget_id",
    )

    raise BudgetNotFoundException(budget_id)          # from a service
    raise BudgetNotFoundException(message="custom")   # from the repository
"""

from typing import Any, TypeVar, cast

from tempest_fastapi_sdk.exceptions.base import AppException
from tempest_fastapi_sdk.exceptions.conflict import ConflictException
from tempest_fastapi_sdk.exceptions.not_found import NotFoundException

DEFAULT_NOT_FOUND_TEMPLATE: str = "{subject} {identifier} not found."
"""Message used when the identifier is known."""

DEFAULT_NOT_FOUND_TEMPLATE_ANONYMOUS: str = "{subject} not found."
"""Message used when the exception is raised without an identifier."""

DEFAULT_CONFLICT_TEMPLATE: str = "{subject} {identifier} already exists."
"""Conflict message used when the identifier is known."""

DEFAULT_CONFLICT_TEMPLATE_ANONYMOUS: str = "{subject} already exists."
"""Conflict message used when no identifier is given."""

ExceptionT = TypeVar("ExceptionT", bound=AppException)


def _class_name(code: str, name: str | None) -> str:
    """Derive the generated class name from the error code.

    ``"BUDGET_NOT_FOUND"`` becomes ``"BudgetNotFoundException"``, which
    is what a traceback, a ``repr`` and every debugger will show.

    Args:
        code (str): The machine-readable error code.
        name (str | None): An explicit name that wins when given.

    Returns:
        str: The class name to create.
    """
    if name is not None:
        return name
    parts = [part for part in code.split("_") if part]
    return "".join(part.capitalize() for part in parts) + "Exception"


def _build(
    base: type[ExceptionT],
    code: str,
    subject: str,
    field: str,
    template: str,
    template_anonymous: str,
    name: str | None,
) -> type[ExceptionT]:
    """Create the exception subclass shared by both public factories.

    Args:
        base (type[ExceptionT]): ``NotFoundException`` or
            ``ConflictException``.
        code (str): The machine-readable error code.
        subject (str): Human-readable name of the resource.
        field (str): Key the identifier is filed under in ``details``.
        template (str): Message template used with an identifier.
        template_anonymous (str): Message template used without one.
        name (str | None): Explicit class name.

    Returns:
        type[ExceptionT]: The generated subclass.
    """

    def __init__(  # noqa: N807
        self: AppException,
        identifier: Any = None,
        *,
        message: str | None = None,
        details: dict[str, Any] | None = None,
        headers: dict[str, str] | None = None,
    ) -> None:
        """Initialize the exception from an identifier, a message, or both.

        Args:
            identifier (Any): The value that matched no record. Rendered
                into the message and filed under the configured field in
                ``details``.
            message (str | None): Overrides the generated message. This
                is the shape ``BaseRepository`` uses.
            details (dict[str, Any] | None): Extra context, merged over
                the identifier entry.
            headers (dict[str, str] | None): Optional HTTP headers.
        """
        if message is None:
            message = (
                template.format(subject=subject, identifier=identifier)
                if identifier is not None
                else template_anonymous.format(subject=subject)
            )
        merged: dict[str, Any] = {}
        if identifier is not None:
            merged[field] = str(identifier)
        if details:
            merged.update(details)
        base.__init__(
            self,
            message=message,
            details=merged,
            headers=headers,
        )

    namespace: dict[str, Any] = {
        "__init__": __init__,
        "__doc__": (
            f"Raised when a {subject.lower()} cannot be resolved.\n\n"
            f"Generated by ``tempest_fastapi_sdk.exceptions``; answers "
            f"``code = {code!r}``."
        ),
        "code": code,
        "message": template_anonymous.format(subject=subject),
        "details_example": {field: "..."},
    }
    return cast(
        "type[ExceptionT]",
        type(_class_name(code, name), (base,), namespace),
    )


def not_found_exception(
    code: str,
    *,
    subject: str = "Resource",
    field: str = "id",
    template: str = DEFAULT_NOT_FOUND_TEMPLATE,
    template_anonymous: str = DEFAULT_NOT_FOUND_TEMPLATE_ANONYMOUS,
    name: str | None = None,
) -> type[NotFoundException]:
    """Build a domain-specific 404 exception class.

    The returned class is a real
    :class:`~tempest_fastapi_sdk.exceptions.NotFoundException` subclass —
    it declares ``code`` in its body, so
    :func:`~tempest_fastapi_sdk.error_responses` documents it and no
    :class:`~tempest_fastapi_sdk.InheritedErrorCodeWarning` is raised —
    and it accepts both call shapes::

        BudgetNotFoundException = not_found_exception(
            "BUDGET_NOT_FOUND",
            subject="Orcamento",
            field="budget_id",
        )

        BudgetNotFoundException("abc").detail
        # 'Orcamento abc not found.'
        BudgetNotFoundException("abc").details
        # {'budget_id': 'abc'}
        BudgetNotFoundException(message="Nao encontrado.").detail
        # 'Nao encontrado.'

    Accepting ``message=`` is not cosmetic: ``BaseRepository`` raises
    ``self.not_found_exception(message=...)``, so a hand-written class
    whose ``__init__`` takes only the id answers every repository miss
    with a ``TypeError`` — a 500 instead of a 404.

    Localize by keying a
    :class:`~tempest_fastapi_sdk.exceptions.MessageCatalog` on ``code``,
    or by writing the templates in the project's language.

    Args:
        code (str): Stable machine-readable identifier, e.g.
            ``"BUDGET_NOT_FOUND"``. Also the default catalog key.
        subject (str): Human-readable name of the resource, interpolated
            as ``{subject}``.
        field (str): Key the identifier is filed under in ``details``.
        template (str): Message template used when an identifier is
            given. Receives ``{subject}`` and ``{identifier}``.
        template_anonymous (str): Message template used when it is not.
            Receives ``{subject}``.
        name (str | None): Class name. Defaults to the code in
            PascalCase plus ``Exception``.

    Returns:
        type[NotFoundException]: The generated exception class.
    """
    return _build(
        NotFoundException,
        code,
        subject,
        field,
        template,
        template_anonymous,
        name,
    )


def conflict_exception(
    code: str,
    *,
    subject: str = "Resource",
    field: str = "id",
    template: str = DEFAULT_CONFLICT_TEMPLATE,
    template_anonymous: str = DEFAULT_CONFLICT_TEMPLATE_ANONYMOUS,
    name: str | None = None,
) -> type[ConflictException]:
    """Build a domain-specific 409 exception class.

    The 409 twin of :func:`not_found_exception`, for the same reason:
    ``BaseRepository`` raises its conflict classes as
    ``exception_class(message=...)`` too, from the
    ``create_conflict_exception`` / ``update_conflict_exception`` slots::

        EmailTakenException = conflict_exception(
            "EMAIL_TAKEN",
            subject="Email",
            field="email",
            template="{identifier} is already registered.",
        )

        repository = UserRepository(
            session,
            create_conflict_exception=EmailTakenException,
        )

    Args:
        code (str): Stable machine-readable identifier.
        subject (str): Human-readable name of the resource.
        field (str): Key the identifier is filed under in ``details``.
        template (str): Message template used with an identifier.
        template_anonymous (str): Message template used without one.
        name (str | None): Class name. Defaults to the code in
            PascalCase plus ``Exception``.

    Returns:
        type[ConflictException]: The generated exception class.
    """
    return _build(
        ConflictException,
        code,
        subject,
        field,
        template,
        template_anonymous,
        name,
    )


__all__: list[str] = [
    "DEFAULT_CONFLICT_TEMPLATE",
    "DEFAULT_CONFLICT_TEMPLATE_ANONYMOUS",
    "DEFAULT_NOT_FOUND_TEMPLATE",
    "DEFAULT_NOT_FOUND_TEMPLATE_ANONYMOUS",
    "conflict_exception",
    "not_found_exception",
]
