"""The generated ``env.py`` driven by the bare ``alembic`` CLI.

Every case scaffolds a project with :meth:`AlembicHelper.init`, writes a
model module with an enum column used by two tables, and runs
``python -m alembic`` in a subprocess from the project root — the way
``uv run alembic downgrade -1`` runs, without the ``tempest`` CLI and
without any ``PYTHONPATH``. That covers three issues end to end:

* #451: the metadata import resolves through ``prepend_sys_path = .``
  (the control removes the line and gets ``ModuleNotFoundError``).
* #453: the autogenerated ``create_table`` carries no explicit
  ``CheckConstraint`` for the enum column, and SQLite still ends up with
  exactly one ``CHECK``, named by the convention.
* #454: the downgrade drops the ``ENUM`` type, so ``upgrade`` →
  ``downgrade`` → ``upgrade`` passes on PostgreSQL (marked ``docker``,
  run with ``make test-docker`` or ``TEST_POSTGRES_URL``).
"""

from __future__ import annotations

import asyncio
import os
import shutil
import sqlite3
import subprocess
import sys
import time
from collections.abc import Iterator
from pathlib import Path

import pytest
import sqlalchemy as sa
from sqlalchemy.ext.asyncio import create_async_engine

from tempest_fastapi_sdk import AlembicHelper

MODELS: str = '''"""Models for the generated-env tests."""

import enum

from sqlalchemy.orm import Mapped

from tempest_fastapi_sdk import BaseModel


class UserRole(enum.StrEnum):
    """Roles shared by both tables."""

    GUARDIAN = "GUARDIAN"
    TEEN = "TEEN"


class ThingModel(BaseModel):
    """First table holding the enum."""

    __tablename__ = "things"

    role: Mapped[UserRole]


class OtherModel(BaseModel):
    """Second table holding the same enum."""

    __tablename__ = "others"

    role: Mapped[UserRole]
'''
"""A model module whose two tables share one native enum type."""

POSTGRES_IMAGE: str = "postgres:16-alpine"
POSTGRES_CONTAINER: str = "tempest-alembic-env-live"
POSTGRES_PORT: int = 55463


def _scaffold(root: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """Scaffold an Alembic project whose metadata comes from ``envmodels``.

    The scaffold runs from the project root, so ``script_location`` is
    the relative ``alembic`` a real project gets.

    Args:
        root (Path): The project root.
        monkeypatch (pytest.MonkeyPatch): Moves the working directory.

    Returns:
        Path: The same root, now holding ``alembic.ini``, ``alembic/``
        and the ``envmodels`` package.
    """
    package = root / "envmodels"
    package.mkdir()
    (package / "__init__.py").write_text(MODELS, encoding="utf-8")
    monkeypatch.chdir(root)
    AlembicHelper(config_path=str(root / "alembic.ini")).init(
        directory="alembic",
        metadata_module="envmodels",
    )
    return root


def _alembic(
    root: Path, database_url: str, *args: str
) -> subprocess.CompletedProcess[str]:
    """Run the bare Alembic CLI from the project root.

    ``-P`` keeps ``python -m`` from putting the working directory on
    ``sys.path``, which the ``alembic`` console script never does, and
    ``PYTHONPATH`` is removed: only ``prepend_sys_path`` can make the
    project importable. The interpreter's ``bin`` directory leads
    ``PATH`` so the ``ruff`` post-write hooks resolve.

    Args:
        root (Path): The project root.
        database_url (str): The ``DATABASE_URL`` the env resolves.
        *args (str): The Alembic command and its arguments.

    Returns:
        subprocess.CompletedProcess[str]: The finished process.
    """
    env = {key: value for key, value in os.environ.items() if key != "PYTHONPATH"}
    env["DATABASE_URL"] = database_url
    env["PATH"] = f"{Path(sys.executable).parent}{os.pathsep}{env.get('PATH', '')}"
    return subprocess.run(
        [sys.executable, "-P", "-m", "alembic", *args],
        cwd=root,
        env=env,
        capture_output=True,
        text=True,
        timeout=120,
    )


def _ok(process: subprocess.CompletedProcess[str]) -> None:
    """Fail with the process output when it did not exit cleanly.

    Args:
        process (subprocess.CompletedProcess[str]): The finished process.
    """
    assert process.returncode == 0, f"{process.stdout}\n{process.stderr}"


def _revision_source(root: Path) -> str:
    """Read the single revision autogenerate wrote.

    Args:
        root (Path): The project root.

    Returns:
        str: The revision file's source.
    """
    (revision,) = (root / "alembic" / "versions").glob("*.py")
    return revision.read_text(encoding="utf-8")


@pytest.fixture
def project(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """Yield a freshly scaffolded project.

    Args:
        tmp_path (Path): Pytest's per-test directory.
        monkeypatch (pytest.MonkeyPatch): Moves the working directory.

    Returns:
        Path: The project root.
    """
    return _scaffold(tmp_path, monkeypatch)


class TestBareAlembicCli:
    def test_round_trip_on_sqlite(self, project: Path) -> None:
        url = f"sqlite+aiosqlite:///{project / 'app.db'}"
        _ok(_alembic(project, url, "revision", "--autogenerate", "-m", "init"))
        source = _revision_source(project)
        assert "CheckConstraint" not in source
        assert source.count("op.drop_enum_type(") == 1
        assert "op.drop_enum_type('user_role_enum')" in source.replace('"', "'")

        _ok(_alembic(project, url, "upgrade", "head"))
        _ok(_alembic(project, url, "downgrade", "-1"))
        _ok(_alembic(project, url, "upgrade", "head"))

        with sqlite3.connect(project / "app.db") as connection:
            (ddl,) = connection.execute(
                "SELECT sql FROM sqlite_master WHERE name = 'things'"
            ).fetchone()
        assert ddl.count("CHECK") == 1
        assert "CONSTRAINT ck_things_user_role_enum CHECK" in ddl

    def test_metadata_import_needs_prepend_sys_path(self, project: Path) -> None:
        """Control: without the ini line the bare CLI cannot import the models."""
        ini = project / "alembic.ini"
        lines = ini.read_text(encoding="utf-8").splitlines()
        assert "prepend_sys_path = ." in lines
        ini.write_text(
            "\n".join(line for line in lines if not line.startswith("prepend_")),
            encoding="utf-8",
        )
        url = f"sqlite+aiosqlite:///{project / 'app.db'}"
        process = _alembic(project, url, "upgrade", "head")
        assert process.returncode != 0
        assert "No module named 'envmodels'" in process.stderr

    def test_custom_revision_hook_replaces_the_default(self, project: Path) -> None:
        env_py = project / "alembic" / "env.py"
        source = env_py.read_text(encoding="utf-8")
        env_py.write_text(
            source.replace(
                "run_alembic_env(target_metadata)",
                "def _empty(context, revision, directives):\n"
                "    directives[0].upgrade_ops.ops.clear()\n"
                "    directives[0].downgrade_ops.ops.clear()\n\n\n"
                "run_alembic_env(target_metadata, "
                "process_revision_directives=_empty)",
            ),
            encoding="utf-8",
        )
        url = f"sqlite+aiosqlite:///{project / 'app.db'}"
        _ok(_alembic(project, url, "revision", "--autogenerate", "-m", "empty"))
        source = _revision_source(project)
        assert "create_table" not in source
        assert "drop_enum_type" not in source


@pytest.fixture(scope="module")
def postgres_url() -> Iterator[str]:
    """Yield a PostgreSQL URL: ``TEST_POSTGRES_URL`` or a fresh container.

    Yields:
        str: An asyncpg URL to an empty database.
    """
    configured = os.environ.get("TEST_POSTGRES_URL")
    if configured:
        yield configured
        return
    if shutil.which("docker") is None:
        pytest.skip("docker CLI not installed")
    if subprocess.run(["docker", "info"], capture_output=True).returncode != 0:
        pytest.skip("docker daemon not reachable")
    subprocess.run(["docker", "rm", "-f", POSTGRES_CONTAINER], capture_output=True)
    started = subprocess.run(
        [
            "docker",
            "run",
            "-d",
            "--name",
            POSTGRES_CONTAINER,
            "-e",
            "POSTGRES_PASSWORD=probe",
            "-e",
            "POSTGRES_DB=probe",
            "-p",
            f"{POSTGRES_PORT}:5432",
            POSTGRES_IMAGE,
        ],
        capture_output=True,
        text=True,
    )
    if started.returncode != 0:
        pytest.skip(f"could not start {POSTGRES_IMAGE}: {started.stderr.strip()}")
    try:
        deadline = time.monotonic() + 60
        while time.monotonic() < deadline:
            ready = subprocess.run(
                ["docker", "exec", POSTGRES_CONTAINER, "pg_isready", "-U", "postgres"],
                capture_output=True,
            )
            if ready.returncode == 0:
                break
            time.sleep(0.5)
        yield f"postgresql+asyncpg://postgres:probe@127.0.0.1:{POSTGRES_PORT}/probe"
    finally:
        subprocess.run(["docker", "rm", "-f", POSTGRES_CONTAINER], capture_output=True)


def _enum_types(url: str) -> list[str]:
    """List the enum types in the PostgreSQL database.

    Args:
        url (str): The asyncpg URL.

    Returns:
        list[str]: The ``typname`` of every enum type, sorted.
    """

    async def _read() -> list[str]:
        """Read ``pg_type`` over an async engine.

        Returns:
            list[str]: The enum type names, sorted.
        """
        engine = create_async_engine(url)
        try:
            async with engine.connect() as connection:
                rows = await connection.execute(
                    sa.text("SELECT typname FROM pg_type WHERE typtype = 'e'")
                )
                return sorted(row[0] for row in rows)
        finally:
            await engine.dispose()

    return asyncio.run(_read())


@pytest.mark.docker
def test_upgrade_downgrade_upgrade_on_postgresql(
    project: Path, postgres_url: str
) -> None:
    """The type leaves with the last table, so the second upgrade recreates it."""
    _ok(_alembic(project, postgres_url, "revision", "--autogenerate", "-m", "init"))
    assert "CheckConstraint" not in _revision_source(project)

    _ok(_alembic(project, postgres_url, "upgrade", "head"))
    assert _enum_types(postgres_url) == ["user_role_enum"]
    _ok(_alembic(project, postgres_url, "downgrade", "base"))
    assert _enum_types(postgres_url) == []
    _ok(_alembic(project, postgres_url, "upgrade", "head"))
    assert _enum_types(postgres_url) == ["user_role_enum"]
    _ok(_alembic(project, postgres_url, "downgrade", "base"))
