"""The enum pieces of an autogenerated migration: the CHECK and the downgrade.

Two defects, both measured against a real PostgreSQL 16:

* Under SQLAlchemy 2.1 the autogenerated ``create_table`` carried two
  explicit ``CheckConstraint`` per enum column, both renamed by the
  naming convention to ``ck_<table>_<enum>``, and PostgreSQL refused the
  second (#453). :func:`render_enum_types` now omits the type-bound one.
* The autogenerated downgrade of a table with an enum column was only
  ``op.drop_table``, which leaves the ``ENUM`` type behind, so the next
  ``upgrade`` failed with ``type ... already exists`` (#454).
  :func:`drop_enum_types_on_downgrade` appends ``op.drop_enum_type``.

The end-to-end runs (bare ``alembic`` CLI, SQLite and PostgreSQL) live in
``test_alembic_env.py``; this module pins the pieces.
"""

from __future__ import annotations

from types import SimpleNamespace
from typing import Any

import sqlalchemy as sa
from alembic.autogenerate import render_python_code
from alembic.migration import MigrationContext
from alembic.operations import Operations
from alembic.operations.ops import (
    CreateTableOp,
    DowngradeOps,
    DropTableOp,
    MigrationScript,
    UpgradeOps,
)

from tempest_fastapi_sdk.db.enum_migrations import (
    DropEnumTypeOp,
    drop_enum_types_on_downgrade,
    render_enum_types,
)
from tempest_fastapi_sdk.db.enums import TempestEnum
from tempest_fastapi_sdk.db.model import NAMING_CONVENTION

ROLE_VALUES: tuple[str, ...] = ("GUARDIAN", "TEEN")


def _metadata(*tables: str, shared: bool = True) -> sa.MetaData:
    """Build tables that each hold an enum column named ``role``.

    Args:
        *tables (str): The table names.
        shared (bool): Whether the tables share one enum type; when
            ``False`` each gets its own ``<table>_role_enum``.

    Returns:
        sa.MetaData: The metadata, under the SDK naming convention.
    """
    metadata = sa.MetaData(naming_convention=NAMING_CONVENTION)
    for name in tables:
        enum_name = "user_role_enum" if shared else f"{name}_role_enum"
        sa.Table(
            name,
            metadata,
            sa.Column("id", sa.Integer, primary_key=True),
            sa.Column("role", TempestEnum(*ROLE_VALUES, name=enum_name)),
        )
    return metadata


def _script(
    downgrade: list[Any],
) -> MigrationScript:
    """Wrap downgrade operations in a migration script.

    Args:
        downgrade (list[Any]): The downgrade operations.

    Returns:
        MigrationScript: A script with an empty upgrade.
    """
    return MigrationScript(
        rev_id="r1",
        upgrade_ops=UpgradeOps(ops=[]),
        downgrade_ops=DowngradeOps(ops=downgrade),
    )


def _run_hook(metadata: sa.MetaData | None, script: MigrationScript) -> list[Any]:
    """Run the hook the way Alembic does and return the downgrade ops.

    Args:
        metadata (sa.MetaData | None): The ``target_metadata`` option.
        script (MigrationScript): The script to amend.

    Returns:
        list[Any]: The downgrade operations after the hook ran.
    """
    context = SimpleNamespace(opts={"target_metadata": metadata})
    drop_enum_types_on_downgrade(context, "r1", [script])
    assert script.downgrade_ops is not None
    return list(script.downgrade_ops.ops)


def _drops(ops: list[Any]) -> list[str]:
    """List the enum types the downgrade drops, in order.

    Args:
        ops (list[Any]): Downgrade operations.

    Returns:
        list[str]: The names of every :class:`DropEnumTypeOp`.
    """
    return [op.name for op in ops if isinstance(op, DropEnumTypeOp)]


class TestTypeBoundCheckIsOmitted:
    def test_the_enum_check_is_omitted(self) -> None:
        """The CHECK SQLAlchemy attaches through the enum type renders as nothing.

        Returning ``False`` (the pre-#453 behaviour) handed it back to
        Alembic, whose own filter misses it under SQLAlchemy 2.1.
        """
        table = _metadata("things").tables["things"]
        checks = [c for c in table.constraints if isinstance(c, sa.CheckConstraint)]
        assert len(checks) == 1
        assert render_enum_types("check", checks[0], None) is None  # type: ignore[arg-type]

    def test_the_boolean_check_is_omitted(self) -> None:
        metadata = sa.MetaData(naming_convention=NAMING_CONVENTION)
        table = sa.Table(
            "flags",
            metadata,
            sa.Column("on", sa.Boolean(create_constraint=True, name="on_bool")),
        )
        checks = [c for c in table.constraints if isinstance(c, sa.CheckConstraint)]
        assert len(checks) == 1
        assert render_enum_types("check", checks[0], None) is None  # type: ignore[arg-type]

    def test_a_declared_check_keeps_rendering(self) -> None:
        """A business rule in ``__table_args__`` is not type bound."""
        metadata = sa.MetaData(naming_convention=NAMING_CONVENTION)
        declared = sa.CheckConstraint("amount > 0", name="positive_amount")
        sa.Table("orders", metadata, sa.Column("amount", sa.Integer), declared)
        assert render_enum_types("check", declared, None) is False  # type: ignore[arg-type]

    def test_rendered_create_table_has_no_enum_check_but_keeps_the_declared_one(
        self,
    ) -> None:
        metadata = _metadata("things")
        table = metadata.tables["things"]
        table.append_constraint(sa.CheckConstraint("id > 0", name="positive_id"))
        code = render_python_code(
            UpgradeOps(ops=[CreateTableOp.from_table(table)]),
            render_item=render_enum_types,
        )
        assert code.count("CheckConstraint(") == 1
        assert "id > 0" in code
        assert "role IN" not in code
        assert "create_constraint=True" in code


class TestDropEnumTypeOp:
    @staticmethod
    def _offline_sql(dialect: str, operation: DropEnumTypeOp) -> str:
        """Run the operation in offline mode and return the emitted SQL.

        Args:
            dialect (str): The dialect name.
            operation (DropEnumTypeOp): The operation to run.

        Returns:
            str: Everything written to the offline buffer.
        """
        from io import StringIO

        buffer = StringIO()
        context = MigrationContext.configure(
            dialect_name=dialect,
            opts={"as_sql": True, "output_buffer": buffer},
        )
        Operations(context).invoke(operation)
        return buffer.getvalue()

    def test_postgresql_drops_the_type_if_it_exists(self) -> None:
        sql = self._offline_sql("postgresql", DropEnumTypeOp("user_role_enum"))
        assert "DROP TYPE IF EXISTS user_role_enum" in sql

    def test_schema_and_quoting_are_applied(self) -> None:
        sql = self._offline_sql(
            "postgresql", DropEnumTypeOp("User Role", schema="tenant")
        )
        assert 'DROP TYPE IF EXISTS tenant."User Role"' in sql

    def test_sqlite_emits_nothing(self) -> None:
        assert self._offline_sql("sqlite", DropEnumTypeOp("user_role_enum")) == ""

    def test_it_is_callable_as_op_drop_enum_type(self) -> None:
        engine = sa.create_engine("sqlite://")
        with engine.begin() as connection:
            operations = Operations(MigrationContext.configure(connection))
            operations.drop_enum_type("user_role_enum")  # type: ignore[attr-defined]

    def test_renders_as_the_call(self) -> None:
        code = render_python_code(
            DowngradeOps(
                ops=[
                    DropEnumTypeOp("user_role_enum"),
                    DropEnumTypeOp("tenant_enum", schema="tenant"),
                ]
            ),
        )
        assert "op.drop_enum_type('user_role_enum')" in code
        assert "op.drop_enum_type('tenant_enum', schema='tenant')" in code


class TestDropEnumTypesOnDowngrade:
    def test_new_table_drops_its_type_after_the_table(self) -> None:
        metadata = _metadata("things")
        ops = _run_hook(
            metadata,
            _script([DropTableOp.from_table(metadata.tables["things"])]),
        )
        assert isinstance(ops[0], DropTableOp)
        assert _drops(ops) == ["user_role_enum"]
        assert isinstance(ops[-1], DropEnumTypeOp)

    def test_shared_type_stays_while_another_table_uses_it(self) -> None:
        metadata = _metadata("things", "others")
        ops = _run_hook(
            metadata,
            _script([DropTableOp.from_table(metadata.tables["things"])]),
        )
        assert _drops(ops) == []

    def test_shared_type_is_dropped_once_when_the_last_table_leaves(self) -> None:
        metadata = _metadata("things", "others")
        ops = _run_hook(
            metadata,
            _script(
                [
                    DropTableOp.from_table(metadata.tables["things"]),
                    DropTableOp.from_table(metadata.tables["others"]),
                ]
            ),
        )
        assert _drops(ops) == ["user_role_enum"]

    def test_a_table_the_downgrade_recreates_keeps_the_type(self) -> None:
        """A table the upgrade dropped comes back in the downgrade."""
        metadata = _metadata("things")
        legacy = sa.Table(
            "legacy",
            sa.MetaData(),
            sa.Column("id", sa.Integer, primary_key=True),
            sa.Column("role", sa.Enum(*ROLE_VALUES, name="user_role_enum")),
        )
        ops = _run_hook(
            metadata,
            _script(
                [
                    DropTableOp.from_table(metadata.tables["things"]),
                    CreateTableOp.from_table(legacy),
                ]
            ),
        )
        assert _drops(ops) == []

    def test_each_type_of_the_dropped_table_is_considered(self) -> None:
        metadata = _metadata("things", "others", shared=False)
        ops = _run_hook(
            metadata,
            _script(
                [
                    DropTableOp.from_table(metadata.tables["things"]),
                    DropTableOp.from_table(metadata.tables["others"]),
                ]
            ),
        )
        assert sorted(_drops(ops)) == ["others_role_enum", "things_role_enum"]

    def test_non_native_enum_has_no_type_to_drop(self) -> None:
        metadata = sa.MetaData()
        table = sa.Table(
            "plain",
            metadata,
            sa.Column("id", sa.Integer, primary_key=True),
            sa.Column("role", sa.Enum(*ROLE_VALUES, name="r", native_enum=False)),
        )
        ops = _run_hook(metadata, _script([DropTableOp.from_table(table)]))
        assert _drops(ops) == []

    def test_sequence_of_metadata_is_accepted(self) -> None:
        first = _metadata("things")
        second = _metadata("others")
        ops = _run_hook(
            [first, second],  # type: ignore[arg-type]
            _script([DropTableOp.from_table(first.tables["things"])]),
        )
        assert _drops(ops) == []

    def test_without_metadata_nothing_changes(self) -> None:
        table = _metadata("things").tables["things"]
        ops = _run_hook(None, _script([DropTableOp.from_table(table)]))
        assert _drops(ops) == []

    def test_empty_directives_are_ignored(self) -> None:
        context = SimpleNamespace(opts={"target_metadata": _metadata("things")})
        drop_enum_types_on_downgrade(context, "r1", [])
