"""The enum autogenerate tests under the SQLAlchemy that broke them.

The lock resolves SQLAlchemy 2.0.52, where Alembic still recognizes the
``CHECK`` an enum type attaches (``constraint._create_rule.target``) and
leaves it out of the migration on its own — so on the lock, the test
that the autogenerated ``create_table`` has no ``CheckConstraint``
passes with or without the fix. Under SQLAlchemy 2.1.4 with Alembic
1.20.0, ``_create_rule`` is a ``functools.partial`` without ``target``,
and the migration came out with two explicit ``CheckConstraint`` per
enum column (#453). This module reruns the two enum modules there, in a
subprocess with both pins overlaid by ``uv run --with`` — the mold of
``test_integrity_sqlalchemy_matrix.py``: ``python -m pytest`` (the
``pytest`` script's shebang would import the lock's SQLAlchemy),
versions probed before the run, ``--no-sync`` so the extras survive.

Marked ``network``: the overlay resolves the pins from the index on a
cold cache.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

ROOT: Path = Path(__file__).resolve().parents[2]
MODULES: tuple[str, ...] = (
    "tests/db/test_enum_downgrade.py",
    "tests/db/test_alembic_env.py",
)
PINS: dict[str, str] = {"sqlalchemy": "2.1.4", "alembic": "1.20.0"}
"""The first pair measured to render the duplicate ``CheckConstraint``."""


def _uv_run(*command: str) -> subprocess.CompletedProcess[str]:
    """Run ``command`` with :data:`PINS` overlaid on the project.

    Args:
        *command (str): The command, starting with ``python``.

    Returns:
        subprocess.CompletedProcess[str]: The finished process.
    """
    overlay = [
        arg
        for name, version in PINS.items()
        for arg in ("--with", f"{name}=={version}")
    ]
    return subprocess.run(
        ["uv", "run", "--no-sync", *overlay, *command],
        cwd=ROOT,
        capture_output=True,
        text=True,
        timeout=600,
    )


@pytest.mark.network
def test_enum_autogenerate_tests_pass_under_sqlalchemy_21() -> None:
    if shutil.which("uv") is None:
        pytest.skip("uv not installed")

    probe = _uv_run(
        "python",
        "-c",
        "import alembic, sqlalchemy; "
        "print(sqlalchemy.__version__, alembic.__version__)",
    )
    assert probe.returncode == 0, probe.stderr
    assert probe.stdout.split() == [PINS["sqlalchemy"], PINS["alembic"]]

    run = _uv_run(
        "python",
        "-m",
        "pytest",
        *MODULES,
        "-p",
        "no:cacheprovider",
        "--no-cov",
        "-q",
    )
    assert run.returncode == 0, f"{run.stdout}\n{run.stderr}"
    assert " passed" in run.stdout
