"""Guard: the ``env.py`` that ``tempest db init`` writes passes a service's lint.

Through 0.308.0 the generated file failed ``ruff check --select E,W,F,I``
(``I001`` twice, ``E402`` on the metadata import placed after code) and
carried 21 lines of inline comments, which the services' convention
forbids. One service rewrote it by hand and lost the ``sys.path``
handling with it (#451).

The generated file is linted here inside a scaffolded project, from the
project root, under two configurations that classify the ``alembic``
import differently: the ``[tool.ruff]`` of the ``tempest new`` template
(``src = ["src", "tests"]``, so ``alembic`` is third-party) and ruff's
defaults (``src = [".", "src"]``, where the ``alembic/`` directory makes
it first-party). No static import order of ``from alembic import
context`` satisfies both, which is why the generated file imports no
``alembic`` at all.
"""

from __future__ import annotations

import io
import re
import subprocess
import sys
import tokenize
from pathlib import Path

import pytest

from tempest_fastapi_sdk import AlembicHelper

PACKAGE: Path = Path(__file__).resolve().parent.parent / "tempest_fastapi_sdk"
"""Root of the shipped package."""

SCAFFOLD_PYPROJECT: Path = PACKAGE / "cli" / "_templates" / "pyproject.toml.tmpl"
"""The ``pyproject.toml`` that ``tempest new`` writes."""

MACHINE_MARKERS: tuple[str, ...] = ("# type:", "# noqa", "# pragma:")
"""Comment prefixes aimed at tools, which the no-comment rule allows."""

SHIPPED_0_308_HEAD: str = '''"""Alembic environment script.

Generated by tempest-fastapi-sdk. Edit the metadata import below
when your project moves the BaseModel re-export.
"""

import asyncio
import os
import sys
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from tempest_fastapi_sdk.db.alembic_hooks import (
    backfill_non_nullable_defaults,
    compose_hooks,
    reorder_base_columns_first,
)
from tempest_fastapi_sdk.db.enum_migrations import (
    render_enum_types,
    sync_enum_types,
)
from tempest_fastapi_sdk.db.migrations import require_sqlite_foreign_keys_off

# Hooks that normalize every autogenerated revision.
_process_revision_directives = compose_hooks(
    reorder_base_columns_first,
    backfill_non_nullable_defaults,
    sync_enum_types,
)

# >>> tempest-fastapi-sdk: metadata import (edit if needed) <<<
from src.db.models import BaseModel
target_metadata = BaseModel.metadata
# >>> end tempest-fastapi-sdk block <<<

config = context.config
print(asyncio, os, sys, fileConfig, Path, pool, Connection)
print(async_engine_from_config, render_enum_types, require_sqlite_foreign_keys_off)
'''
"""The head of the 0.308.0 ``env.py.template``, as ``tempest db init`` wrote it."""


def _scaffold_ruff_config() -> str:
    """Extract the ``[tool.ruff*]`` sections of the ``tempest new`` template.

    Returns:
        str: The sections, ready to be a project's ``pyproject.toml``.
    """
    text = SCAFFOLD_PYPROJECT.read_text(encoding="utf-8")
    start = text.index("[tool.ruff]")
    end = text.index("\n[tool.", text.index("[tool.ruff.format]"))
    return text[start:end] + "\n"


def _project(root: Path, configuration: str, metadata_module: str | None) -> Path:
    """Scaffold a project and return its generated ``env.py``.

    Args:
        root (Path): The project root.
        configuration (str): ``"scaffold"`` for the ``tempest new`` ruff
            config, ``"default"`` for ruff's defaults.
        metadata_module (str | None): Passed to :meth:`AlembicHelper.init`.

    Returns:
        Path: The generated ``alembic/env.py``.
    """
    (root / "src" / "db" / "models").mkdir(parents=True)
    if configuration == "scaffold":
        (root / "pyproject.toml").write_text(_scaffold_ruff_config(), encoding="utf-8")
    AlembicHelper(config_path=str(root / "alembic.ini")).init(
        directory=str(root / "alembic"),
        metadata_module=metadata_module,
    )
    return root / "alembic" / "env.py"


def lint(env_py: Path, *, select: str | None = None) -> list[str]:
    """Run ruff on ``env_py`` from its project root.

    A project without ``pyproject.toml`` is linted with ``--isolated``,
    so ruff's defaults apply instead of whatever configuration sits
    above the temporary directory or in the user's home.

    Args:
        env_py (Path): The file to lint, inside ``<root>/alembic/``.
        select (str | None): A ``--select`` override; ``None`` lints with
            the project's own configuration.

    Returns:
        list[str]: The rule codes reported, in order.

    Raises:
        AssertionError: When ruff itself fails (exit code 2 or more), so
            a missing ruff cannot pass as a clean file.
    """
    root = env_py.parent.parent
    command = [sys.executable, "-m", "ruff", "check", "--no-cache"]
    command += ["--output-format", "concise"]
    if not (root / "pyproject.toml").exists():
        command.append("--isolated")
    if select is not None:
        command += ["--select", select]
    result = subprocess.run(
        [*command, str(env_py)],
        cwd=root,
        capture_output=True,
        text=True,
        timeout=60,
    )
    assert result.returncode in (0, 1), result.stderr
    return re.findall(r":\d+:\d+: ([A-Z]+\d+)", result.stdout)


def inline_comments(source: str) -> list[str]:
    """List the comments in ``source`` that are prose, not tool markers.

    Args:
        source (str): Python source.

    Returns:
        list[str]: Every comment token not starting with a machine marker.
    """
    tokens = tokenize.generate_tokens(io.StringIO(source).readline)
    return [
        token.string
        for token in tokens
        if token.type == tokenize.COMMENT
        and not token.string.startswith(MACHINE_MARKERS)
    ]


@pytest.mark.parametrize("configuration", ["scaffold", "default"])
@pytest.mark.parametrize("metadata_module", ["src.db.models", None])
def test_generated_env_py_is_lint_clean(
    tmp_path: Path, configuration: str, metadata_module: str | None
) -> None:
    env_py = _project(tmp_path, configuration, metadata_module)
    assert lint(env_py, select="E,W,F,I") == []
    if configuration == "scaffold":
        assert lint(env_py) == []


@pytest.mark.parametrize("metadata_module", ["src.db.models", None])
def test_generated_env_py_has_no_inline_comment(
    tmp_path: Path, metadata_module: str | None
) -> None:
    env_py = _project(tmp_path, "scaffold", metadata_module)
    assert inline_comments(env_py.read_text(encoding="utf-8")) == []


@pytest.mark.parametrize("configuration", ["scaffold", "default"])
def test_guard_fires_on_the_0_308_template(tmp_path: Path, configuration: str) -> None:
    """The file as it shipped is reported under both configurations."""
    env_py = _project(tmp_path, configuration, "src.db.models")
    env_py.write_text(SHIPPED_0_308_HEAD, encoding="utf-8")
    codes = lint(env_py, select="E,W,F,I")
    assert "E402" in codes
    assert "I001" in codes
    assert len(inline_comments(SHIPPED_0_308_HEAD)) == 3


def test_machine_markers_are_not_inline_comments() -> None:
    source = "import x  # noqa: F401\ny = 1  # type: ignore[assignment]\n"
    assert inline_comments(source) == []
