"""tempest-fastapi-sdk — shared FastAPI/SQLAlchemy/Pydantic primitives."""

from tempest_fastapi_sdk.api import (
    app_exception_handler,
    register_exception_handlers,
)
from tempest_fastapi_sdk.db import (
    NAMING_CONVENTION,
    AlembicHelper,
    AsyncDatabaseManager,
    BaseModel,
    BaseRepository,
)
from tempest_fastapi_sdk.exceptions import (
    AppException,
    ConflictException,
    ExpiredTokenException,
    FileTooLargeException,
    ForbiddenException,
    InvalidFileTypeException,
    InvalidTokenException,
    NotFoundException,
    UnauthorizedException,
    ValidationException,
)
from tempest_fastapi_sdk.schemas import (
    BasePaginationFilterSchema,
    BasePaginationSchema,
    BaseResponseSchema,
    BaseSchema,
)
from tempest_fastapi_sdk.settings import BaseAppSettings
from tempest_fastapi_sdk.utils import (
    CNPJ,
    CNPJ_PATTERN,
    CPF,
    CPF_CNPJ_PATTERN,
    CPF_PATTERN,
    PHONE_BR_PATTERN,
    CPFOrCNPJ,
    EmailUtils,
    JWTUtils,
    PasswordUtils,
    PhoneBR,
    UploadUtils,
    is_valid_cnpj,
    is_valid_cpf,
    is_valid_cpf_cnpj,
    is_valid_phone_br,
    modify_dict,
    normalize_cnpj,
    normalize_cpf,
    normalize_cpf_cnpj,
    normalize_phone_br,
    only_digits,
    to_utc,
    utcnow,
)

__version__: str = "0.2.0"

__all__: list[str] = [
    "CNPJ",
    "CNPJ_PATTERN",
    "CPF",
    "CPF_CNPJ_PATTERN",
    "CPF_PATTERN",
    "NAMING_CONVENTION",
    "PHONE_BR_PATTERN",
    "AlembicHelper",
    "AppException",
    "AsyncDatabaseManager",
    "BaseAppSettings",
    "BaseModel",
    "BasePaginationFilterSchema",
    "BasePaginationSchema",
    "BaseRepository",
    "BaseResponseSchema",
    "BaseSchema",
    "CPFOrCNPJ",
    "ConflictException",
    "EmailUtils",
    "ExpiredTokenException",
    "FileTooLargeException",
    "ForbiddenException",
    "InvalidFileTypeException",
    "InvalidTokenException",
    "JWTUtils",
    "NotFoundException",
    "PasswordUtils",
    "PhoneBR",
    "UnauthorizedException",
    "UploadUtils",
    "ValidationException",
    "__version__",
    "app_exception_handler",
    "is_valid_cnpj",
    "is_valid_cpf",
    "is_valid_cpf_cnpj",
    "is_valid_phone_br",
    "modify_dict",
    "normalize_cnpj",
    "normalize_cpf",
    "normalize_cpf_cnpj",
    "normalize_phone_br",
    "only_digits",
    "register_exception_handlers",
    "to_utc",
    "utcnow",
]
