"""The whole OpenPix surface, ready to import.

`pip install tempest-fastapi-sdk` and you have all 373 OpenPix schemas and
all 105 operations, plus the four things the specification does not say.
Nobody runs a generator, and nobody re-derives by hand which header carries
the webhook signature.

.. code-block:: python

    from tempest_fastapi_sdk import HTTPClient
    from tempest_fastapi_sdk.integrations.payment.openpix import (
        Charge,
        OpenPixClient,
        OpenPixEnvironment,
        to_cents,
    )

    http: HTTPClient = HTTPClient(
        base_url=OpenPixEnvironment.SANDBOX.base_url,
        default_headers={"Authorization": "<your AppID>"},
    )
    client: OpenPixClient = OpenPixClient(http)

The generated half is **checked in, not written by hand**:
``scripts/regen_openpix.py`` produces it from the pinned specification in
``vendor/openpix-openapi.json``, and a test fails if the files on disk drift
from what that script produces. Editing them directly is how checked-in
generated code rots.

Two halves, and it is worth knowing which is which:

- **Generated** — ``OpenPixClient``, ``DEFAULT_BASE_URL`` and the 373
  schema classes. Whatever the specification says, verbatim.
- **Hand-written** — ``OpenPixEnvironment`` (the spec's two hosts are
  different domains), ``OpenPixEvent`` (28 webhook events), the webhook
  verification, and the money helpers, because the spec says *"Value in
  cents"* and then types the field ``number``.

!!! note "The schemas load on first use, not on import"
    Building 373 Pydantic models is the expensive part. Importing this package
    for ``to_cents`` alone should not pay it, so the generated modules are
    resolved lazily through :pep:`562`.

    Measured on Python 3.11 with ``tempest_fastapi_sdk`` already imported:
    ~11 ms to import this subpackage, ~150 ms on the first access to a
    generated name, ~0.02 ms after that. Machine-dependent numbers; the ratio
    is the point.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from tempest_fastapi_sdk.integrations.payment.openpix.environment import (
    OpenPixEnvironment as OpenPixEnvironment,
)
from tempest_fastapi_sdk.integrations.payment.openpix.events import (
    OpenPixEvent as OpenPixEvent,
)
from tempest_fastapi_sdk.integrations.payment.openpix.money import (
    cents_to_reais as cents_to_reais,
)
from tempest_fastapi_sdk.integrations.payment.openpix.money import (
    reais_to_cents as reais_to_cents,
)
from tempest_fastapi_sdk.integrations.payment.openpix.money import to_cents as to_cents
from tempest_fastapi_sdk.integrations.payment.openpix.webhooks import (
    OPENPIX_WEBHOOK_PUBLIC_KEY as OPENPIX_WEBHOOK_PUBLIC_KEY,
)
from tempest_fastapi_sdk.integrations.payment.openpix.webhooks import (
    OPENPIX_WEBHOOK_SIGNATURE_HEADER as OPENPIX_WEBHOOK_SIGNATURE_HEADER,
)
from tempest_fastapi_sdk.integrations.payment.openpix.webhooks import (
    OpenPixWebhookEvent as OpenPixWebhookEvent,
)
from tempest_fastapi_sdk.integrations.payment.openpix.webhooks import (
    decode_public_key as decode_public_key,
)
from tempest_fastapi_sdk.integrations.payment.openpix.webhooks import (
    make_openpix_webhook_dependency as make_openpix_webhook_dependency,
)
from tempest_fastapi_sdk.integrations.payment.openpix.webhooks import (
    webhook_verifier as webhook_verifier,
)

if TYPE_CHECKING:  # pragma: no cover - import-time cost is the point
    from tempest_fastapi_sdk.integrations.payment.openpix.client import (
        DEFAULT_BASE_URL as DEFAULT_BASE_URL,
    )
    from tempest_fastapi_sdk.integrations.payment.openpix.client import (
        OpenPixClient as OpenPixClient,
    )
    from tempest_fastapi_sdk.integrations.payment.openpix.schemas import *  # noqa: F403

_HAND_WRITTEN: tuple[str, ...] = (
    "OPENPIX_WEBHOOK_PUBLIC_KEY",
    "OPENPIX_WEBHOOK_SIGNATURE_HEADER",
    "OpenPixEnvironment",
    "OpenPixEvent",
    "OpenPixWebhookEvent",
    "cents_to_reais",
    "decode_public_key",
    "make_openpix_webhook_dependency",
    "reais_to_cents",
    "to_cents",
    "webhook_verifier",
)
"""Names this package defines itself, always eagerly available."""


_GENERATED_MODULES: tuple[str, ...] = ("schemas", "client")
"""Submodules holding the generated code, in dependency order."""


def _generated_names() -> dict[str, str]:
    """Map every generated name to the submodule that defines it.

    Returns:
        dict[str, str]: ``{name: submodule}``, built by importing the
        generated modules. Called only from :func:`__getattr__` and
        :func:`__dir__`, so importing this package does not trigger it.

    Imports go through :func:`importlib.import_module` rather than
    ``from . import schemas``. The ``from`` form asks the **package** for
    the attribute, which lands back in :func:`__getattr__`, which calls
    this — unbounded recursion, and the traceback blames the last frame
    rather than the loop.
    """
    from importlib import import_module

    mapping: dict[str, str] = {}
    for module_name in _GENERATED_MODULES:
        module = import_module(f"{__name__}.{module_name}")
        mapping.update(dict.fromkeys(module.__all__, module_name))
    return mapping


def __getattr__(name: str) -> Any:
    """Resolve a generated name, or a generated submodule, on first access.

    Args:
        name (str): The attribute being looked up.

    Returns:
        Any: The generated class, client, constant or submodule.

    Raises:
        AttributeError: If no generated module defines ``name``.

    The 373 schema classes are resolved through this hook rather than
    imported at module level: the list is regenerated from the
    specification, and importing them eagerly would build every model on
    ``import``. The cost is that a **typo** also loads the generated
    modules before failing — paid once, on an access that was going to
    raise anyway.
    """
    from importlib import import_module

    if name in _GENERATED_MODULES:
        module = import_module(f"{__name__}.{name}")
        globals()[name] = module
        return module

    module_name = _generated_names().get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(f"{__name__}.{module_name}"), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    """List everything importable from this package.

    Returns:
        list[str]: Hand-written names plus every generated one, sorted, so
        autocompletion and ``help()`` see the whole surface.

    This does load the generated modules. That is the right trade: someone
    running ``dir()`` is exploring the API, which is exactly when the full
    list is worth the wait.
    """
    return sorted({*_HAND_WRITTEN, *_generated_names()})


__all__: list[str] = [
    "DEFAULT_BASE_URL",
    "OPENPIX_WEBHOOK_PUBLIC_KEY",
    "OPENPIX_WEBHOOK_SIGNATURE_HEADER",
    "AccountLimit",
    "AccountObjectPayload",
    "AccountRegister",
    "AccountRegisterPayload",
    "AccountRegisterResponse",
    "AccountRegisterResponseTaxId",
    "AccountRegisterTaxId",
    "ActivateAnticipationBeneficiaryResponse",
    "AnticipationBalanceBatchPayload",
    "AnticipationBalanceBatchPayloadItemsItem",
    "AnticipationBalanceBatchResult",
    "AnticipationBalanceBatchResultResultsItem",
    "AnticipationBeneficiary",
    "AnticipationBeneficiaryCreatePayload",
    "AnticipationBeneficiaryCreatePayloadFrequencyOverride",
    "AnticipationBeneficiaryTaxId",
    "AnticipationBeneficiaryTaxIdType",
    "AnticipationError",
    "AnticipationRequest",
    "AnticipationRequestStatus",
    "AnticipationUnauthorized",
    "AnticipationUnauthorizedErrorsItem",
    "Application",
    "ApplicationDeletePayload",
    "ApplicationEnumTypePayload",
    "ApplicationPayload",
    "ApplicationPayloadApplication",
    "ApplicationPayloadApplicationType",
    "ApplicationType",
    "ApproveAnticipationResponse",
    "ApprovePaymentResponse",
    "ApproveStablecoinDepositBody",
    "ApproveStablecoinDepositResponse",
    "BoletoTransaction",
    "BoletoTransactionCharge",
    "BoletoTransactionError",
    "BoletoTransactionListResponse",
    "BoletoTransactionListResponsePageInfo",
    "BoletoTransactionStatus",
    "BoletoTransactionType",
    "BoletoValidateError",
    "BoletoValidateRequest",
    "BoletoValidateResponse",
    "BoletoValidatedInfo",
    "BoletoValidatedInfoFinalBeneficiary",
    "BoletoValidatedInfoIssuingEntity",
    "CancelInvoiceResponse",
    "Charge",
    "ChargeAdditionalInfoItem",
    "ChargePatchPayload",
    "ChargePayload",
    "ChargePayloadAdditionalInfoItem",
    "ChargePayloadDiscountSettings",
    "ChargePayloadDiscountSettingsDiscountFixedDateItem",
    "ChargePayloadDiscountSettingsModality",
    "ChargePayloadFines",
    "ChargePayloadInterests",
    "ChargePayloadInterestsType",
    "ChargePayloadSplitsItem",
    "ChargePayloadSplitsItemSplitType",
    "ChargePaymentMethods",
    "ChargePaymentMethodsPix",
    "ChargePaymentMethodsPixAdditionalInfoItem",
    "ChargeRefund",
    "ChargeRefundPayload",
    "ChargeRefundStatus",
    "ChargeStatus",
    "ChargeType",
    "CheckPixKeyBody",
    "CloseAccountResponse",
    "Company",
    "CompanyBankAccount",
    "CompanyBankAccountBalance",
    "CompanyObjectPayload",
    "CompanyResponse",
    "CreateAnticipationBeneficiaryResponse",
    "CreateApplicationResponse",
    "CreateCashbackFidelityBody",
    "CreateCashbackFidelityResponse",
    "CreateCashbackFidelityResponseCashback",
    "CreateChargeResponse",
    "CreateCustomerResponse",
    "CreateInstallmentCobrBody",
    "CreateInvoiceResponse",
    "CreateInvoiceResponseInvoice",
    "CreateInvoiceResponseInvoiceCharge",
    "CreateInvoiceResponseInvoiceCustomer",
    "CreateKycOnboardingResponse",
    "CreatePartnerApplicationBody",
    "CreatePartnerApplicationBodyApplication",
    "CreatePartnerApplicationResponse",
    "CreatePaymentBody",
    "CreatePaymentBodyBoleto",
    "CreatePaymentBodyManual",
    "CreatePaymentBodyManualAccount",
    "CreatePaymentBodyManualHolder",
    "CreatePaymentBodyManualHolderTaxId",
    "CreatePaymentBodyPixKey",
    "CreatePaymentBodyQrCode",
    "CreatePaymentResponse",
    "CreateRefundResponse",
    "CreateStablecoinPayoutBody",
    "CreateStablecoinPayoutResponse",
    "CreateStablecoinPayoutResponsePixKeyOwner",
    "CreateStablecoinPayoutResponseQuote",
    "CreateStaticQrCodeResponse",
    "CreateSubaccountResponse",
    "CreateSubscriptionResponse",
    "CreateTransferResponse",
    "CreateWebhookBody",
    "CreateWebhookResponse",
    "CreditSubaccountBody",
    "CreditSubaccountResponse",
    "Customer",
    "CustomerAddress",
    "CustomerPatchPayload",
    "CustomerPatchPayloadAddress",
    "CustomerPayload",
    "CustomerPayloadAddress",
    "CustomerTaxId",
    "DeactivateAnticipationBeneficiaryResponse",
    "DebitSubaccountBody",
    "DebitSubaccountResponse",
    "DecodeEmvBody",
    "DecodeEmvResponse",
    "DecodeEmvResponseCobLocation",
    "DecodeEmvResponseCobLocationPayload",
    "DecodeEmvResponseCobLocationPayloadAdditionalInfoItem",
    "DecodeEmvResponseCobLocationPayloadCalendar",
    "DecodeEmvResponseCobLocationPayloadDebtor",
    "DecodeEmvResponseCobLocationPayloadValue",
    "DecodeEmvResponseEmv",
    "DecodeEmvResponseEmvAdditionalDataFieldTemplate",
    "DecodeEmvResponseEmvMerchantAccountInformationPix",
    "DecodeEmvResponseEmvUnreservedTemplates",
    "DecodeEmvResponseRecLocation",
    "DecodeEmvResponseRecLocationPayload",
    "DecodeEmvResponseRecLocationPayloadCalendar",
    "DecodeEmvResponseRecLocationPayloadLink",
    "DecodeEmvResponseRecLocationPayloadLinkDebtor",
    "DecodeEmvResponseRecLocationPayloadReceiver",
    "DecodeEmvResponseRecLocationPayloadUpdatesItem",
    "DecodeEmvResponseRecLocationPayloadValue",
    "DeleteAccountRegisterResponse",
    "DeleteApplicationResponse",
    "DeleteChargeResponse",
    "DeleteStaticQrCodeResponse",
    "DeleteSubaccountResponse",
    "DeleteWebhookResponse",
    "Dispute",
    "DisputePayload",
    "DisputePayloadStatus",
    "DisputeStatus",
    "DuplicateAccountResponse",
    "Error",
    "ErrorResponse",
    "File",
    "FileContentType",
    "FileError",
    "FilePayload",
    "FilePurpose",
    "FraudMarkers",
    "FundsRecovery",
    "FundsRecoveryDirection",
    "FundsRecoveryEventsItem",
    "FundsRecoveryPayload",
    "FundsRecoverySituationType",
    "FundsRecoveryStatus",
    "GetAccountLimitsResponse",
    "GetAccountRegisterResponse",
    "GetAccountRegisterResponseTaxId",
    "GetAccountResponse",
    "GetBoletoTransactionResponse",
    "GetCashbackFidelityBalanceResponse",
    "GetChargeQrCodeBase64Response",
    "GetChargeResponse",
    "GetCompanyResponse",
    "GetCompanyResponseCompany",
    "GetCustomerResponse",
    "GetDisputeResponse",
    "GetDisputeResponseDispute",
    "GetDisputeResponseDisputeStatus",
    "GetDisputeResponseDisputeType",
    "GetInstallmentResponse",
    "GetPartnerCompanyResponse",
    "GetPartnerCompanyResponsePreRegistration",
    "GetPaymentResponse",
    "GetReceiptReceiptType",
    "GetRefundResponse",
    "GetStablecoinQuoteResponse",
    "GetStablecoinQuoteResponseQuote",
    "GetStablecoinQuoteResponseQuoteAppliedFeesItem",
    "GetStablecoinSubaccountBalancesResponse",
    "GetStatementResponseItem",
    "GetStaticQrCodeResponse",
    "GetSubaccountResponse",
    "GetSubaccountStatementResponseItem",
    "GetSubaccountStatementResponseItemOperationType",
    "GetSubaccountStatementResponseItemType",
    "GetSubscriptionResponse",
    "GetTransactionResponse",
    "InfractionReports",
    "Installment",
    "InstallmentCobr",
    "InstallmentCobrTriesItem",
    "KeyOrOwnerStatistics",
    "KycOnboardingAccountRegister",
    "KycOnboardingAccountRegisterRepresentativesItem",
    "KycOnboardingAccountRegisterRepresentativesItemTaxId",
    "KycOnboardingAccountRegisterTaxId",
    "KycOnboardingRepresentative",
    "KycOnboardingRequest",
    "KycValidation",
    "KycValidationError",
    "KycValidationReasonsItem",
    "KycValidationRequest",
    "KycValidationResult",
    "KycValidationRiskLevel",
    "KycValidationStatus",
    "ListAccountsResponse",
    "ListAccountsResponsePageInfo",
    "ListAccountsResponsePageInfoErrorsItem",
    "ListAccountsResponsePageInfoErrorsItemData",
    "ListAnticipationRequestsResponse",
    "ListChargeRefundsResponse",
    "ListChargesResponse",
    "ListChargesResponsePageInfo",
    "ListChargesResponsePageInfoErrorsItem",
    "ListChargesResponsePageInfoErrorsItemData",
    "ListCustomersResponse",
    "ListCustomersResponsePageInfo",
    "ListCustomersResponsePageInfoErrorsItem",
    "ListCustomersResponsePageInfoErrorsItemData",
    "ListDisputesResponse",
    "ListDisputesResponseDisputesItem",
    "ListDisputesResponseDisputesItemType",
    "ListDisputesResponsePageInfo",
    "ListDisputesResponsePageInfoErrorsItem",
    "ListDisputesResponsePageInfoErrorsItemData",
    "ListPartnerAffiliatesResponse",
    "ListPartnerAffiliatesResponseAffiliatesItem",
    "ListPartnerAffiliatesResponsePageInfo",
    "ListPartnerAffiliatesResponsePageInfoErrorsItem",
    "ListPartnerAffiliatesResponsePageInfoErrorsItemData",
    "ListPartnerCompaniesResponse",
    "ListPartnerCompaniesResponsePageInfo",
    "ListPartnerCompaniesResponsePageInfoErrorsItem",
    "ListPartnerCompaniesResponsePageInfoErrorsItemData",
    "ListPartnerCompaniesResponsePreRegistrationsItem",
    "ListPaymentsResponse",
    "ListPaymentsResponsePageInfo",
    "ListPaymentsResponsePageInfoErrorsItem",
    "ListPaymentsResponsePageInfoErrorsItemData",
    "ListPaymentsResponsePaymentsItem",
    "ListPixKeyTokenLogsResponse",
    "ListPixKeyTokenLogsResponsePageInfo",
    "ListPixKeyTokenLogsResponsePageInfoErrorsItem",
    "ListPixKeyTokenLogsResponsePageInfoErrorsItemData",
    "ListPixKeysResponse",
    "ListPspsResponse",
    "ListPspsResponsePspsItem",
    "ListRefundsResponse",
    "ListRefundsResponsePageInfo",
    "ListRefundsResponsePageInfoErrorsItem",
    "ListRefundsResponsePageInfoErrorsItemData",
    "ListStablecoinSubaccountWalletsResponse",
    "ListStablecoinSubaccountWalletsResponseWalletsItem",
    "ListStablecoinWalletsResponse",
    "ListStablecoinWalletsResponseWalletsItem",
    "ListStaticQrCodesResponse",
    "ListStaticQrCodesResponsePageInfo",
    "ListStaticQrCodesResponsePageInfoErrorsItem",
    "ListStaticQrCodesResponsePageInfoErrorsItemData",
    "ListSubaccountsResponse",
    "ListSubaccountsResponsePageInfo",
    "ListSubaccountsResponsePageInfoErrorsItem",
    "ListSubaccountsResponsePageInfoErrorsItemData",
    "ListSubaccountsResponseSubaccountsItem",
    "ListSubscriptionInstallmentsResponse",
    "ListSubscriptionsResponse",
    "ListTransactionsResponse",
    "ListTransactionsResponsePageInfo",
    "ListTransactionsResponsePageInfoErrorsItem",
    "ListTransactionsResponsePageInfoErrorsItemData",
    "ListTransactionsType",
    "ListWebhookEventsResponse",
    "ListWebhookEventsResponseEventsItem",
    "ListWebhookIpsResponse",
    "ListWebhookPublicKeysResponse",
    "ListWebhookPublicKeysResponsePublicKeysItem",
    "ListWebhooksResponse",
    "ListWebhooksResponsePageInfo",
    "ListWebhooksResponsePageInfoErrorsItem",
    "ListWebhooksResponsePageInfoErrorsItemData",
    "NumericWindow",
    "OpenPixClient",
    "OpenPixEnvironment",
    "OpenPixEvent",
    "OpenPixWebhookEvent",
    "Pagination",
    "PaginationErrorsItem",
    "PaginationErrorsItemData",
    "PartnerApplicationPayload",
    "Party",
    "PartyAccount",
    "PartyHolder",
    "PartyPsp",
    "PartyTaxId",
    "PayloadAccount",
    "Payment",
    "PaymentApprovePayload",
    "PaymentBoleto",
    "PaymentBoletoFinalBeneficiary",
    "PaymentBoletoIssuingEntity",
    "PaymentCreatePayload",
    "PaymentCreatePayloadBoleto",
    "PaymentCreatePayloadManual",
    "PaymentCreatePayloadManualAccount",
    "PaymentCreatePayloadManualHolder",
    "PaymentCreatePayloadManualHolderTaxId",
    "PaymentCreatePayloadPixKey",
    "PaymentCreatePayloadPixKeyDestinationAliasType",
    "PaymentCreatePayloadPixKeyType",
    "PaymentCreatePayloadQrCode",
    "PaymentDestination",
    "PaymentStatus",
    "PaymentTransaction",
    "PixKey",
    "PixKeyCheck",
    "PixKeyCheckOwner",
    "PixKeyCreate",
    "PixKeyCreateType",
    "PixKeyFraudValidationData",
    "PixKeyFraudValidationResponse",
    "PixKeyTokens",
    "PixKeyType",
    "PixQrCode",
    "PixQrCodePayload",
    "PixWithdrawTransaction",
    "PreRegistrationObject",
    "PreRegistrationObjectPayload",
    "PreRegistrationPayloadObject",
    "PreRegistrationUserObject",
    "Psp",
    "QuoteStablecoinPayoutResponse",
    "QuoteStablecoinPayoutResponseQuote",
    "Refund",
    "RefundChargeResponse",
    "RefundPayload",
    "RefundStatus",
    "RejectAnticipationBody",
    "RejectAnticipationResponse",
    "RetryInstallmentCobrBody",
    "SetInvoiceIntegrationStatusBody",
    "SetInvoiceIntegrationStatusResponse",
    "SetInvoiceIntegrationStatusResponseIntegration",
    "StablecoinDepositError",
    "StablecoinDepositGetResponse",
    "StablecoinDepositListItem",
    "StablecoinDepositListResponse",
    "StablecoinDepositQuote",
    "StablecoinDepositRequest",
    "StablecoinDepositRequestCurrency",
    "StablecoinDepositRequestNetwork",
    "StablecoinDepositResponse",
    "StablecoinSubAccountCreateError",
    "StablecoinSubAccountCreateRequest",
    "StablecoinSubAccountCreateResponse",
    "StablecoinSubAccountGetResponse",
    "StablecoinSubAccountItem",
    "StablecoinSubAccountListResponse",
    "SubAccount",
    "SubAccountPayload",
    "SubAccountTransferPayload",
    "SubAccountTransferResponsePayload",
    "SubAccountTransferResponsePayloadDestinationSubaccount",
    "SubAccountTransferResponsePayloadOriginSubaccount",
    "SubAccountWithdrawPayload",
    "Subscription",
    "SubscriptionAddtionalInfoItem",
    "SubscriptionFrequency",
    "SubscriptionPayload",
    "SubscriptionPayloadAdditionalInfoItem",
    "SubscriptionPayloadCustomer",
    "SubscriptionPayloadCustomerAddress",
    "SubscriptionPayloadPixRecurringOptions",
    "SubscriptionPayloadType",
    "SubscriptionPixRecurringOptions",
    "SubscriptionPixRecurringOptionsJourney",
    "SubscriptionPixRecurringOptionsRetryPolicy",
    "SubscriptionPixRecurringOptionsStatus",
    "SubscriptionType",
    "TaxIdObjectPayload",
    "TaxIdObjectPayloadType",
    "TestInvoiceIntegrationResponse",
    "TestInvoiceIntegrationResponseIntegration",
    "TestInvoiceIntegrationResponseInvoice",
    "TokenBucketLog",
    "TokenBucketLogOperation",
    "Transaction",
    "Transaction2",
    "TransactionStatus",
    "TransactionType",
    "TransactionWebhookSentItem",
    "TransferCreatePayload",
    "TransferTransaction",
    "UpdateChargeResponse",
    "UpdateCustomerResponse",
    "UpdateInvoiceIntegrationTaxFieldsBody",
    "UpdateInvoiceIntegrationTaxFieldsResponse",
    "UploadDisputeEvidenceBody",
    "UploadDisputeEvidenceBodyDocumentsItem",
    "UploadDisputeEvidenceResponse",
    "UploadDisputeEvidenceResponseDocumentsItem",
    "UploadInvoiceIntegrationCertificateBody",
    "UploadInvoiceIntegrationCertificateResponse",
    "UploadInvoiceIntegrationCertificateResponseIntegration",
    "UpsertInvoiceIntegrationBody",
    "UpsertInvoiceIntegrationResponse",
    "UpsertInvoiceIntegrationResponseIntegration",
    "UpsertInvoiceIntegrationResponseIntegrationMetadata",
    "UpsertInvoiceIntegrationResponseIntegrationMetadataNfei",
    "Webhook",
    "WebhookAccountRegisterApprovedPayload",
    "WebhookAccountRegisterApprovedPayloadAccount",
    "WebhookAccountRegisterApprovedPayloadAccountRegister",
    "WebhookAccountRegisterApprovedPayloadAccountRegisterTax",
    "WebhookAccountRegisterPendingPayload",
    "WebhookAccountRegisterPendingPayloadAccountRegister",
    "WebhookAccountRegisterPendingPayloadAccountRegisterRequ",
    "WebhookAccountRegisterPendingPayloadAccountRegisterRequ2",
    "WebhookAccountRegisterPendingPayloadAccountRegisterTaxI",
    "WebhookAccountRegisterRejectedPayload",
    "WebhookAccountRegisterRejectedPayloadAccountRegister",
    "WebhookAccountRegisterRejectedPayloadAccountRegisterTax",
    "WebhookBoletoSettledPayload",
    "WebhookBoletoSettledPayloadBoleto",
    "WebhookBoletoSettledPayloadCharge",
    "WebhookCharge",
    "WebhookChargeAdditionalInfoItem",
    "WebhookChargeCustomer",
    "WebhookChargeCustomerTaxId",
    "WebhookChargePayer",
    "WebhookChargePayerTaxId",
    "WebhookCompanyBankAccountBlockedPayload",
    "WebhookCompanyBankAccountBlockedPayloadAccount",
    "WebhookCompanyBankAccountBlockedPayloadAccountTaxId",
    "WebhookCompanyBankAccountBlockedPayloadBlockingsItem",
    "WebhookEventEnum",
    "WebhookOpenpixChargeCompletedNotSameCustomerPayerPayloa",
    "WebhookOpenpixChargeCompletedNotSameCustomerPayerPayloa2",
    "WebhookOpenpixChargeCompletedNotSameCustomerPayerPayloa3",
    "WebhookOpenpixChargeCompletedNotSameCustomerPayerPayloa4",
    "WebhookOpenpixChargeCompletedNotSameCustomerPayerPayloa5",
    "WebhookOpenpixChargeCompletedNotSameCustomerPayerPayloa6",
    "WebhookOpenpixChargeCompletedNotSameCustomerPayerPayloa7",
    "WebhookOpenpixChargeCompletedNotSameCustomerPayerPayloa8",
    "WebhookOpenpixChargeCompletedNotSameCustomerPayerPayloa9",
    "WebhookOpenpixChargeCompletedNotSameCustomerPayerPayloa10",
    "WebhookOpenpixChargeCompletedPayload",
    "WebhookOpenpixChargeCompletedPayloadAccount",
    "WebhookOpenpixChargeCompletedPayloadCompany",
    "WebhookOpenpixChargeCompletedPayloadPix",
    "WebhookOpenpixChargeCompletedPayloadPixCustomer",
    "WebhookOpenpixChargeCompletedPayloadPixCustomerTaxId",
    "WebhookOpenpixChargeCompletedPayloadPixPayer",
    "WebhookOpenpixChargeCompletedPayloadPixPayerTaxId",
    "WebhookOpenpixChargeCreatedPayload",
    "WebhookOpenpixChargeCreatedPayloadAccount",
    "WebhookOpenpixChargeCreatedPayloadCompany",
    "WebhookOpenpixChargeExpiredPayload",
    "WebhookOpenpixChargeExpiredPayloadAccount",
    "WebhookOpenpixChargeExpiredPayloadCompany",
    "WebhookOpenpixDisputeAcceptedPayload",
    "WebhookOpenpixDisputeAcceptedPayloadDispute",
    "WebhookOpenpixDisputeCanceledPayload",
    "WebhookOpenpixDisputeCanceledPayloadDispute",
    "WebhookOpenpixDisputeCreatedPayload",
    "WebhookOpenpixDisputeCreatedPayloadDispute",
    "WebhookOpenpixDisputeRejectedPayload",
    "WebhookOpenpixDisputeRejectedPayloadDispute",
    "WebhookOpenpixMovementConfirmedPayload",
    "WebhookOpenpixMovementConfirmedPayloadPayment",
    "WebhookOpenpixMovementConfirmedPayloadTransaction",
    "WebhookOpenpixMovementFailedPayload",
    "WebhookOpenpixMovementFailedPayloadError",
    "WebhookOpenpixMovementFailedPayloadPayment",
    "WebhookOpenpixMovementFailedPayloadTransaction",
    "WebhookOpenpixMovementRemovedPayload",
    "WebhookOpenpixMovementRemovedPayloadPayment",
    "WebhookOpenpixTransactionReceivedPayload",
    "WebhookOpenpixTransactionReceivedPayloadAccount",
    "WebhookOpenpixTransactionReceivedPayloadCompany",
    "WebhookOpenpixTransactionReceivedPayloadPix",
    "WebhookOpenpixTransactionReceivedPayloadPixCreditParty",
    "WebhookOpenpixTransactionReceivedPayloadPixCreditPartyA",
    "WebhookOpenpixTransactionReceivedPayloadPixCreditPartyH",
    "WebhookOpenpixTransactionReceivedPayloadPixCreditPartyH2",
    "WebhookOpenpixTransactionReceivedPayloadPixCreditPartyP",
    "WebhookOpenpixTransactionReceivedPayloadPixCreditPartyP2",
    "WebhookOpenpixTransactionReceivedPayloadPixDebitParty",
    "WebhookOpenpixTransactionReceivedPayloadPixDebitPartyAc",
    "WebhookOpenpixTransactionReceivedPayloadPixDebitPartyHo",
    "WebhookOpenpixTransactionReceivedPayloadPixDebitPartyHo2",
    "WebhookOpenpixTransactionReceivedPayloadPixDebitPartyPs",
    "WebhookOpenpixTransactionReceivedPayloadPixPayer",
    "WebhookOpenpixTransactionReceivedPayloadPixPayerTaxId",
    "WebhookOpenpixTransactionRefundReceivedPayload",
    "WebhookOpenpixTransactionRefundReceivedPayloadAccount",
    "WebhookOpenpixTransactionRefundReceivedPayloadCompany",
    "WebhookOpenpixTransactionRefundReceivedPayloadPix",
    "WebhookPayload",
    "WebhookPixAutomaticApprovedPayload",
    "WebhookPixAutomaticApprovedPayloadCustomer",
    "WebhookPixAutomaticApprovedPayloadCustomerAddress",
    "WebhookPixAutomaticApprovedPayloadCustomerAddressLocati",
    "WebhookPixAutomaticApprovedPayloadCustomerTaxId",
    "WebhookPixAutomaticApprovedPayloadPixRecurring",
    "WebhookPixAutomaticCobrApprovedPayload",
    "WebhookPixAutomaticCobrApprovedPayloadCobr",
    "WebhookPixAutomaticCobrApprovedPayloadCobrTriesItem",
    "WebhookPixAutomaticCobrCompletedPayload",
    "WebhookPixAutomaticCobrCompletedPayloadCobr",
    "WebhookPixAutomaticCobrCompletedPayloadCobrTriesItem",
    "WebhookPixAutomaticCobrCreatedPayload",
    "WebhookPixAutomaticCobrCreatedPayloadCobr",
    "WebhookPixAutomaticCobrCreatedPayloadCobrTriesItem",
    "WebhookPixAutomaticCobrRejectedPayload",
    "WebhookPixAutomaticCobrRejectedPayloadCobr",
    "WebhookPixAutomaticCobrRejectedPayloadCobrTriesItem",
    "WebhookPixAutomaticCobrTryRejectedPayload",
    "WebhookPixAutomaticCobrTryRejectedPayloadCobr",
    "WebhookPixAutomaticCobrTryRejectedPayloadCobrTriesItem",
    "WebhookPixAutomaticCobrTryRequestedPayload",
    "WebhookPixAutomaticCobrTryRequestedPayloadCobr",
    "WebhookPixAutomaticCobrTryRequestedPayloadCobrTriesItem",
    "WebhookPixAutomaticRejectedPayload",
    "WebhookPixAutomaticRejectedPayloadCustomer",
    "WebhookPixAutomaticRejectedPayloadCustomerAddress",
    "WebhookPixAutomaticRejectedPayloadCustomerAddressLocati",
    "WebhookPixAutomaticRejectedPayloadCustomerTaxId",
    "WebhookPixAutomaticRejectedPayloadPixRecurring",
    "WebhookPixTransactionRefundReceivedConfirmedPayload",
    "WebhookPixTransactionRefundReceivedConfirmedPayloadAcco",
    "WebhookPixTransactionRefundReceivedConfirmedPayloadComp",
    "WebhookPixTransactionRefundReceivedConfirmedPayloadOrig",
    "WebhookPixTransactionRefundReceivedConfirmedPayloadOrig2",
    "WebhookPixTransactionRefundReceivedConfirmedPayloadOrig3",
    "WebhookPixTransactionRefundReceivedConfirmedPayloadOrig4",
    "WebhookPixTransactionRefundReceivedConfirmedPayloadOrig5",
    "WebhookPixTransactionRefundReceivedConfirmedPayloadOrig6",
    "WebhookPixTransactionRefundReceivedConfirmedPayloadOrig7",
    "WebhookPixTransactionRefundReceivedConfirmedPayloadOrig8",
    "WebhookPixTransactionRefundReceivedConfirmedPayloadOrig9",
    "WebhookPixTransactionRefundReceivedConfirmedPayloadOrig10",
    "WebhookPixTransactionRefundReceivedConfirmedPayloadOrig11",
    "WebhookPixTransactionRefundReceivedConfirmedPayloadOrig12",
    "WebhookPixTransactionRefundReceivedConfirmedPayloadOrig13",
    "WebhookPixTransactionRefundReceivedConfirmedPayloadOrig14",
    "WebhookPixTransactionRefundReceivedConfirmedPayloadRefu",
    "WebhookPixTransactionRefundReceivedConfirmedPayloadRefu2",
    "WebhookPixTransactionRefundReceivedConfirmedPayloadRefu3",
    "WebhookPixTransactionRefundReceivedConfirmedPayloadRefu4",
    "WebhookPixTransactionRefundReceivedConfirmedPayloadRefu5",
    "WebhookPixTransactionRefundReceivedConfirmedPayloadRefu6",
    "WebhookPixTransactionRefundReceivedConfirmedPayloadRefu7",
    "WebhookPixTransactionRefundReceivedConfirmedPayloadRefu8",
    "WebhookPixTransactionRefundReceivedConfirmedPayloadRefu9",
    "WebhookPixTransactionRefundReceivedConfirmedPayloadRefu10",
    "WebhookPixTransactionRefundReceivedConfirmedPayloadRefu11",
    "WebhookPixTransactionRefundReceivedConfirmedPayloadRefu12",
    "WebhookPixTransactionRefundReceivedRejectedPayload",
    "WebhookPixTransactionRefundReceivedRejectedPayloadAccou",
    "WebhookPixTransactionRefundReceivedRejectedPayloadCompa",
    "WebhookPixTransactionRefundReceivedRejectedPayloadOrigi",
    "WebhookPixTransactionRefundReceivedRejectedPayloadOrigi2",
    "WebhookPixTransactionRefundReceivedRejectedPayloadOrigi3",
    "WebhookPixTransactionRefundReceivedRejectedPayloadOrigi4",
    "WebhookPixTransactionRefundReceivedRejectedPayloadOrigi5",
    "WebhookPixTransactionRefundReceivedRejectedPayloadOrigi6",
    "WebhookPixTransactionRefundReceivedRejectedPayloadOrigi7",
    "WebhookPixTransactionRefundReceivedRejectedPayloadOrigi8",
    "WebhookPixTransactionRefundReceivedRejectedPayloadOrigi9",
    "WebhookPixTransactionRefundReceivedRejectedPayloadOrigi10",
    "WebhookPixTransactionRefundReceivedRejectedPayloadOrigi11",
    "WebhookPixTransactionRefundReceivedRejectedPayloadOrigi12",
    "WebhookPixTransactionRefundReceivedRejectedPayloadRefun",
    "WebhookPixTransactionRefundReceivedRejectedPayloadRefun2",
    "WebhookPixTransactionRefundReceivedRejectedPayloadRefun3",
    "WebhookPixTransactionRefundReceivedRejectedPayloadRefun4",
    "WebhookPixTransactionRefundReceivedRejectedPayloadRefun5",
    "WebhookPixTransactionRefundReceivedRejectedPayloadRefun6",
    "WebhookPixTransactionRefundReceivedRejectedPayloadRefun7",
    "WebhookPixTransactionRefundReceivedRejectedPayloadRefun8",
    "WebhookPixTransactionRefundReceivedRejectedPayloadRefun9",
    "WebhookPixTransactionRefundReceivedRejectedPayloadRefun10",
    "WebhookPixTransactionRefundReceivedRejectedPayloadRefun11",
    "WebhookPixTransactionRefundReceivedRejectedPayloadRefun12",
    "WebhookPixTransactionRefundSentConfirmedPayload",
    "WebhookPixTransactionRefundSentConfirmedPayloadAccount",
    "WebhookPixTransactionRefundSentConfirmedPayloadCompany",
    "WebhookPixTransactionRefundSentConfirmedPayloadOriginal",
    "WebhookPixTransactionRefundSentConfirmedPayloadOriginal2",
    "WebhookPixTransactionRefundSentConfirmedPayloadOriginal3",
    "WebhookPixTransactionRefundSentConfirmedPayloadOriginal4",
    "WebhookPixTransactionRefundSentConfirmedPayloadOriginal5",
    "WebhookPixTransactionRefundSentConfirmedPayloadOriginal6",
    "WebhookPixTransactionRefundSentConfirmedPayloadOriginal7",
    "WebhookPixTransactionRefundSentConfirmedPayloadOriginal8",
    "WebhookPixTransactionRefundSentConfirmedPayloadOriginal9",
    "WebhookPixTransactionRefundSentConfirmedPayloadOriginal10",
    "WebhookPixTransactionRefundSentConfirmedPayloadOriginal11",
    "WebhookPixTransactionRefundSentConfirmedPayloadOriginal12",
    "WebhookPixTransactionRefundSentConfirmedPayloadOriginal13",
    "WebhookPixTransactionRefundSentConfirmedPayloadOriginal14",
    "WebhookPixTransactionRefundSentConfirmedPayloadRefundTr",
    "WebhookPixTransactionRefundSentConfirmedPayloadRefundTr2",
    "WebhookPixTransactionRefundSentConfirmedPayloadRefundTr3",
    "WebhookPixTransactionRefundSentConfirmedPayloadRefundTr4",
    "WebhookPixTransactionRefundSentConfirmedPayloadRefundTr5",
    "WebhookPixTransactionRefundSentConfirmedPayloadRefundTr6",
    "WebhookPixTransactionRefundSentConfirmedPayloadRefundTr7",
    "WebhookPixTransactionRefundSentConfirmedPayloadRefundTr8",
    "WebhookPixTransactionRefundSentConfirmedPayloadRefundTr9",
    "WebhookPixTransactionRefundSentConfirmedPayloadRefundTr10",
    "WebhookPixTransactionRefundSentConfirmedPayloadRefundTr11",
    "WebhookPixTransactionRefundSentConfirmedPayloadRefundTr12",
    "WebhookPixTransactionRefundSentRejectedPayload",
    "WebhookPixTransactionRefundSentRejectedPayloadAccount",
    "WebhookPixTransactionRefundSentRejectedPayloadCompany",
    "WebhookPixTransactionRefundSentRejectedPayloadOriginalT",
    "WebhookPixTransactionRefundSentRejectedPayloadOriginalT2",
    "WebhookPixTransactionRefundSentRejectedPayloadOriginalT3",
    "WebhookPixTransactionRefundSentRejectedPayloadOriginalT4",
    "WebhookPixTransactionRefundSentRejectedPayloadOriginalT5",
    "WebhookPixTransactionRefundSentRejectedPayloadOriginalT6",
    "WebhookPixTransactionRefundSentRejectedPayloadOriginalT7",
    "WebhookPixTransactionRefundSentRejectedPayloadOriginalT8",
    "WebhookPixTransactionRefundSentRejectedPayloadOriginalT9",
    "WebhookPixTransactionRefundSentRejectedPayloadOriginalT10",
    "WebhookPixTransactionRefundSentRejectedPayloadOriginalT11",
    "WebhookPixTransactionRefundSentRejectedPayloadOriginalT12",
    "WebhookPixTransactionRefundSentRejectedPayloadOriginalT13",
    "WebhookPixTransactionRefundSentRejectedPayloadOriginalT14",
    "WebhookPixTransactionRefundSentRejectedPayloadRefundTra",
    "WebhookPixTransactionRefundSentRejectedPayloadRefundTra2",
    "WebhookPixTransactionRefundSentRejectedPayloadRefundTra3",
    "WebhookPixTransactionRefundSentRejectedPayloadRefundTra4",
    "WebhookPixTransactionRefundSentRejectedPayloadRefundTra5",
    "WebhookPixTransactionRefundSentRejectedPayloadRefundTra6",
    "WebhookPixTransactionRefundSentRejectedPayloadRefundTra7",
    "WebhookPixTransactionRefundSentRejectedPayloadRefundTra8",
    "WebhookPixTransactionRefundSentRejectedPayloadRefundTra9",
    "WebhookPixTransactionRefundSentRejectedPayloadRefundTra10",
    "WebhookPixTransactionRefundSentRejectedPayloadRefundTra11",
    "WebhookPixTransactionRefundSentRejectedPayloadRefundTra12",
    "WebhookStablecoinDepositCompletedPayload",
    "WebhookStablecoinDepositCompletedPayloadCompany",
    "WebhookStablecoinDepositCompletedPayloadStableDeposit",
    "WebhookStablecoinDepositFailedPayload",
    "WebhookStablecoinDepositFailedPayloadCompany",
    "WebhookStablecoinDepositFailedPayloadStableDeposit",
    "WebhookStablecoinPayoutCompletedPayload",
    "WebhookStablecoinPayoutCompletedPayloadCompany",
    "WebhookStablecoinPayoutCompletedPayloadStablePayout",
    "WebhookStablecoinPayoutFailedPayload",
    "WebhookStablecoinPayoutFailedPayloadCompany",
    "WebhookStablecoinPayoutFailedPayloadStablePayout",
    "WebhookStablecoinPayoutRefundConfirmedPayload",
    "WebhookStablecoinPayoutRefundConfirmedPayloadCompany",
    "WebhookStablecoinPayoutRefundConfirmedPayloadRefund",
    "WebhookStablecoinPayoutRefundConfirmedPayloadRefundDest",
    "WebhookStablecoinPayoutRefundConfirmedPayloadRefundStat",
    "WebhookStablecoinPayoutRefundConfirmedPayloadStablePayo",
    "WebhookStablecoinPayoutRefundFailedPayload",
    "WebhookStablecoinPayoutRefundFailedPayloadCompany",
    "WebhookStablecoinPayoutRefundFailedPayloadRefund",
    "WebhookStablecoinPayoutRefundFailedPayloadStablePayout",
    "WebhookStablecoinSubaccountConfirmedPayload",
    "WebhookStablecoinSubaccountConfirmedPayloadCompany",
    "WebhookStablecoinSubaccountConfirmedPayloadStableSubAcc",
    "WebhookStablecoinSubaccountRejectedPayload",
    "WebhookStablecoinSubaccountRejectedPayloadCompany",
    "WebhookStablecoinSubaccountRejectedPayloadStableSubAcco",
    "WithdrawFromAccountBody",
    "WithdrawFromAccountResponse",
    "WithdrawFromAccountResponseWithdraw",
    "WithdrawFromSubaccountResponse",
    "WithdrawFromSubaccountResponseWithdraw",
    "WithdrawTransaction",
    "cents_to_reais",
    "decode_public_key",
    "make_openpix_webhook_dependency",
    "reais_to_cents",
    "to_cents",
    "webhook_verifier",
]
"""The whole surface: the thin layer plus every generated name.

Written by ``scripts/regen_openpix.py`` — the list is the union of
``_HAND_WRITTEN``, ``client.__all__`` and ``schemas.__all__``, and
``tests/integrations/payment/openpix/test_generated_drift.py`` fails when it
drifts from that.

It lists the generated names because a strict type-checker rejects them
otherwise. Measured with basedpyright against the installed wheel: a
consumer writing ``from tempest_fastapi_sdk.integrations.payment.openpix
import ChargePayload`` got *"ChargePayload" is not exported from module*,
with the advice to import from the private ``.schemas`` submodule instead.
The ``TYPE_CHECKING`` wildcard above makes the symbol **visible** but does
not mark it **re-exported**; only ``__all__`` (or an ``X as X`` alias per
name) does. mypy accepted the wildcard either way, which is how this shipped.

The cost is that ``from ... import *`` now pulls every generated name and
pays the lazy load. Importing names explicitly, which is what the rest of
the SDK's docs do, still costs nothing until one of them is a generated one.
"""
