"""The webhook events OpenPix delivers.

Ported verbatim from ``WebhookEventEnum`` in the OpenPix OpenAPI
specification. Read from the specification, never reconstructed from
memory — a typo here silently stops matching a real delivery, and the
handler falls through to "unknown event" instead of failing loudly.

The values are not uniformly prefixed: charge, transaction, movement and
dispute events carry the ``OPENPIX:`` namespace, while the Pix-automatic
and account-register families do not. That is the provider's shape, not a
transcription slip.
"""

from __future__ import annotations

from tempest_fastapi_sdk.core.enums import BaseStrEnum


class OpenPixEvent(BaseStrEnum):
    """A webhook event name as OpenPix sends it in the ``event`` field."""

    CHARGE_CREATED = "OPENPIX:CHARGE_CREATED"
    CHARGE_COMPLETED = "OPENPIX:CHARGE_COMPLETED"
    CHARGE_EXPIRED = "OPENPIX:CHARGE_EXPIRED"
    CHARGE_COMPLETED_NOT_SAME_CUSTOMER_PAYER = (
        "OPENPIX:CHARGE_COMPLETED_NOT_SAME_CUSTOMER_PAYER"
    )
    TRANSACTION_RECEIVED = "OPENPIX:TRANSACTION_RECEIVED"
    TRANSACTION_REFUND_RECEIVED = "OPENPIX:TRANSACTION_REFUND_RECEIVED"
    PIX_TRANSACTION_REFUND_RECEIVED_CONFIRMED = (
        "PIX_TRANSACTION_REFUND_RECEIVED_CONFIRMED"
    )
    PIX_TRANSACTION_REFUND_SENT_CONFIRMED = "PIX_TRANSACTION_REFUND_SENT_CONFIRMED"
    PIX_TRANSACTION_REFUND_RECEIVED_REJECTED = (
        "PIX_TRANSACTION_REFUND_RECEIVED_REJECTED"
    )
    PIX_TRANSACTION_REFUND_SENT_REJECTED = "PIX_TRANSACTION_REFUND_SENT_REJECTED"
    MOVEMENT_CONFIRMED = "OPENPIX:MOVEMENT_CONFIRMED"
    MOVEMENT_FAILED = "OPENPIX:MOVEMENT_FAILED"
    MOVEMENT_REMOVED = "OPENPIX:MOVEMENT_REMOVED"
    DISPUTE_CREATED = "OPENPIX:DISPUTE_CREATED"
    DISPUTE_ACCEPTED = "OPENPIX:DISPUTE_ACCEPTED"
    DISPUTE_REJECTED = "OPENPIX:DISPUTE_REJECTED"
    DISPUTE_CANCELED = "OPENPIX:DISPUTE_CANCELED"
    ACCOUNT_REGISTER_APPROVED = "ACCOUNT_REGISTER_APPROVED"
    ACCOUNT_REGISTER_REJECTED = "ACCOUNT_REGISTER_REJECTED"
    ACCOUNT_REGISTER_PENDING = "ACCOUNT_REGISTER_PENDING"
    PIX_AUTOMATIC_APPROVED = "PIX_AUTOMATIC_APPROVED"
    PIX_AUTOMATIC_REJECTED = "PIX_AUTOMATIC_REJECTED"
    PIX_AUTOMATIC_COBR_CREATED = "PIX_AUTOMATIC_COBR_CREATED"
    PIX_AUTOMATIC_COBR_APPROVED = "PIX_AUTOMATIC_COBR_APPROVED"
    PIX_AUTOMATIC_COBR_REJECTED = "PIX_AUTOMATIC_COBR_REJECTED"
    PIX_AUTOMATIC_COBR_TRY_REJECTED = "PIX_AUTOMATIC_COBR_TRY_REJECTED"
    PIX_AUTOMATIC_COBR_TRY_REQUESTED = "PIX_AUTOMATIC_COBR_TRY_REQUESTED"
    PIX_AUTOMATIC_COBR_COMPLETED = "PIX_AUTOMATIC_COBR_COMPLETED"


__all__: list[str] = ["OpenPixEvent"]
