"""Alembic ``process_revision_directives`` hooks shipped by the SDK.

These hooks let the autogenerated migrations match the conventions
``tempest_fastapi_sdk`` enforces on every model. Wire them in
``env.py`` like this::

    from tempest_fastapi_sdk.db.alembic_hooks import (
        reorder_base_columns_first,
    )

    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        process_revision_directives=reorder_base_columns_first,
        compare_type=True,
        compare_server_default=True,
        render_as_batch=True,
    )

Multiple hooks compose via :func:`compose_hooks`.
"""

from __future__ import annotations

from collections.abc import Callable, Sequence
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from alembic.runtime.migration import MigrationContext

ProcessRevisionDirectives = Callable[
    ["MigrationContext", Any, list[Any]],
    None,
]
"""Alias matching Alembic's ``process_revision_directives`` signature."""

BASE_COLUMN_ORDER: tuple[str, ...] = (
    "id",
    "is_active",
    "created_at",
    "updated_at",
)
"""Columns inherited from ``BaseModel`` — emitted in this exact order at
the top of every ``op.create_table`` produced by autogenerate.
"""


def _is_base_column(item: Any, names: set[str]) -> bool:
    """Return ``True`` when ``item`` is a :class:`sa.Column` we care about.

    Args:
        item (Any): A child of ``CreateTableOp.columns`` — either a
            ``sa.Column`` or a ``sa.Constraint`` subclass.
        names (set[str]): The reorder set.

    Returns:
        bool: ``True`` for matched columns, ``False`` for constraints
        and unrelated columns.
    """
    return getattr(item, "name", None) in names and not _is_constraint(item)


def _is_constraint(item: Any) -> bool:
    """Quick duck-type check — constraints don't expose ``type``."""
    return not hasattr(item, "type")


def reorder_base_columns_first(
    context: MigrationContext,
    revision: Any,
    directives: list[Any],
) -> None:
    """Reorder columns inside every autogenerated ``CreateTableOp``.

    SQLAlchemy stores columns in declaration order, which already
    matches what ``BaseModel`` defines (``id`` →
    ``updated_at``). Autogenerate normally honors that, but
    third-party mixins or class composition can flip the order in
    ways that leak into the migration. This hook normalizes it:

    * The four ``BaseModel`` columns (``id``, ``is_active``,
      ``created_at``, ``updated_at``) come first, in that exact
      order.
    * Constraints stay where Alembic placed them (typically right
      after the columns they reference).
    * Every other column keeps its original relative position.

    Args:
        context (MigrationContext): The active Alembic context.
        revision (Any): The new revision identifier — unused.
        directives (list[Any]): The list of ``MigrationScript``
            directives Alembic will render. Modified in-place.
    """
    del context, revision
    try:
        from alembic.operations import ops
    except ImportError:  # pragma: no cover
        return

    base_set = set(BASE_COLUMN_ORDER)

    def _walk(op_list: Sequence[Any]) -> None:
        for op in op_list:
            if isinstance(op, ops.CreateTableOp):
                op.columns = _reordered_columns(op.columns, base_set)
            # Recurse into nested directives (e.g. ModifyTableOps).
            for attr in ("ops", "upgrade_ops", "downgrade_ops"):
                nested: Any = getattr(op, attr, None)
                if nested is None:
                    continue
                if hasattr(nested, "ops"):
                    _walk(nested.ops)
                elif isinstance(nested, list):
                    _walk(nested)

    for directive in directives:
        if isinstance(directive, ops.MigrationScript):
            if directive.upgrade_ops is not None:
                _walk(directive.upgrade_ops.ops)
            if directive.downgrade_ops is not None:
                _walk(directive.downgrade_ops.ops)


def _reordered_columns(
    items: Sequence[Any],
    base_set: set[str],
) -> list[Any]:
    """Move base columns to the top, keep everything else stable.

    Args:
        items (Sequence[Any]): The ``CreateTableOp.columns`` list —
            mixed ``Column`` + ``Constraint`` instances.
        base_set (set[str]): Names of columns to move to the top.

    Returns:
        list[Any]: A new list with base columns sorted to the front
        in :data:`BASE_COLUMN_ORDER` order, followed by everything
        else in its original relative position.
    """
    base_index = {name: i for i, name in enumerate(BASE_COLUMN_ORDER)}
    base_items: list[Any] = []
    other_items: list[Any] = []
    for item in items:
        if _is_base_column(item, base_set):
            base_items.append(item)
        else:
            other_items.append(item)
    base_items.sort(key=lambda c: base_index[c.name])
    return base_items + other_items


def compose_hooks(
    *hooks: ProcessRevisionDirectives,
) -> ProcessRevisionDirectives:
    """Chain multiple ``process_revision_directives`` hooks.

    Hooks run in the order they're passed and share the same
    ``directives`` list — each can mutate it before the next sees it.

    Args:
        *hooks (ProcessRevisionDirectives): Callables matching the
            Alembic signature.

    Returns:
        ProcessRevisionDirectives: A single callable Alembic can
        register.
    """

    def _combined(
        context: MigrationContext,
        revision: Any,
        directives: list[Any],
    ) -> None:
        for hook in hooks:
            hook(context, revision, directives)

    return _combined


__all__: list[str] = [
    "BASE_COLUMN_ORDER",
    "ProcessRevisionDirectives",
    "compose_hooks",
    "reorder_base_columns_first",
]
