"""Alembic ``process_revision_directives`` hooks shipped by the SDK.

These hooks let the autogenerated migrations match the conventions
``tempest_fastapi_sdk`` enforces on every model. Wire them in
``env.py`` like this::

    from tempest_fastapi_sdk.db.alembic_hooks import (
        reorder_base_columns_first,
    )

    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        process_revision_directives=reorder_base_columns_first,
        compare_type=True,
        compare_server_default=True,
        render_as_batch=True,
    )

Multiple hooks compose via :func:`compose_hooks`.
"""

from __future__ import annotations

from collections.abc import Callable, Sequence
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from alembic.runtime.migration import MigrationContext

ProcessRevisionDirectives = Callable[
    ["MigrationContext", Any, list[Any]],
    None,
]
"""Alias matching Alembic's ``process_revision_directives`` signature."""

BASE_COLUMN_ORDER: tuple[str, ...] = (
    "id",
    "is_active",
    "created_at",
    "updated_at",
)
"""Columns inherited from ``BaseModel`` — emitted in this exact order at
the top of every ``op.create_table`` produced by autogenerate.
"""


def _is_base_column(item: Any, names: set[str]) -> bool:
    """Return ``True`` when ``item`` is a :class:`sa.Column` we care about.

    Args:
        item (Any): A child of ``CreateTableOp.columns`` — either a
            ``sa.Column`` or a ``sa.Constraint`` subclass.
        names (set[str]): The reorder set.

    Returns:
        bool: ``True`` for matched columns, ``False`` for constraints
        and unrelated columns.
    """
    return getattr(item, "name", None) in names and not _is_constraint(item)


def _is_constraint(item: Any) -> bool:
    """Quick duck-type check — constraints don't expose ``type``."""
    return not hasattr(item, "type")


def reorder_base_columns_first(
    context: MigrationContext,
    revision: Any,
    directives: list[Any],
) -> None:
    """Reorder columns inside every autogenerated ``CreateTableOp``.

    SQLAlchemy stores columns in declaration order, which already
    matches what ``BaseModel`` defines (``id`` →
    ``updated_at``). Autogenerate normally honors that, but
    third-party mixins or class composition can flip the order in
    ways that leak into the migration. This hook normalizes it:

    * The four ``BaseModel`` columns (``id``, ``is_active``,
      ``created_at``, ``updated_at``) come first, in that exact
      order.
    * Constraints stay where Alembic placed them (typically right
      after the columns they reference).
    * Every other column keeps its original relative position.

    Args:
        context (MigrationContext): The active Alembic context.
        revision (Any): The new revision identifier — unused.
        directives (list[Any]): The list of ``MigrationScript``
            directives Alembic will render. Modified in-place.
    """
    del context, revision
    try:
        from alembic.operations import ops
    except ImportError:  # pragma: no cover
        return

    base_set = set(BASE_COLUMN_ORDER)

    def _walk(op_list: Sequence[Any]) -> None:
        for op in op_list:
            if isinstance(op, ops.CreateTableOp):
                op.columns = _reordered_columns(op.columns, base_set)
            # Recurse into nested directives (e.g. ModifyTableOps).
            for attr in ("ops", "upgrade_ops", "downgrade_ops"):
                nested: Any = getattr(op, attr, None)
                if nested is None:
                    continue
                if hasattr(nested, "ops"):
                    _walk(nested.ops)
                elif isinstance(nested, list):
                    _walk(nested)

    for directive in directives:
        if isinstance(directive, ops.MigrationScript):
            if directive.upgrade_ops is not None:
                _walk(directive.upgrade_ops.ops)
            if directive.downgrade_ops is not None:
                _walk(directive.downgrade_ops.ops)


def _reordered_columns(
    items: Sequence[Any],
    base_set: set[str],
) -> list[Any]:
    """Move base columns to the top, keep everything else stable.

    Args:
        items (Sequence[Any]): The ``CreateTableOp.columns`` list —
            mixed ``Column`` + ``Constraint`` instances.
        base_set (set[str]): Names of columns to move to the top.

    Returns:
        list[Any]: A new list with base columns sorted to the front
        in :data:`BASE_COLUMN_ORDER` order, followed by everything
        else in its original relative position.
    """
    base_index = {name: i for i, name in enumerate(BASE_COLUMN_ORDER)}
    base_items: list[Any] = []
    other_items: list[Any] = []
    for item in items:
        if _is_base_column(item, base_set):
            base_items.append(item)
        else:
            other_items.append(item)
    base_items.sort(key=lambda c: base_index[c.name])
    return base_items + other_items


_MISSING: Any = object()
"""Sentinel — a column carries no usable scalar default."""


def _scalar_default_literal(value: Any) -> str | None:
    """Render a Python scalar as a SQL ``server_default`` literal.

    Args:
        value (Any): The scalar pulled from a column's Python-side
            ``default`` (``ColumnDefault.arg``). ``Enum`` members are
            unwrapped to their ``.value`` first.

    Returns:
        str | None: A SQL fragment usable inside ``sa.text(...)``
        (``"true"``, ``"42"``, ``"'pending'"``), or ``None`` when the
        value is a type we cannot safely translate (callables, dates,
        JSON, etc. — those need a hand-written data migration).
    """
    from enum import Enum

    if isinstance(value, Enum):
        value = value.value
    # ``bool`` must come before ``int`` — it is a subclass of ``int``.
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        escaped = value.replace("'", "''")
        return f"'{escaped}'"
    return None


def _column_scalar_default(column: Any) -> Any:
    """Return a column's scalar Python default, or :data:`_MISSING`.

    Only *scalar* defaults qualify — a callable (``default=uuid4``),
    a SQL clause element or a sequence cannot be backfilled into a
    ``server_default`` deterministically, so they are skipped.

    Args:
        column (Any): The ``sa.Column`` carried by an ``AddColumnOp``.

    Returns:
        Any: The scalar default value, or :data:`_MISSING` when the
        column has no usable scalar default.
    """
    default = getattr(column, "default", None)
    if default is None:
        return _MISSING
    if not getattr(default, "is_scalar", False):
        return _MISSING
    return default.arg


def backfill_non_nullable_defaults(
    context: MigrationContext,
    revision: Any,
    directives: list[Any],
) -> None:
    """Give every added ``NOT NULL`` column a backfilling ``server_default``.

    Adding a ``NOT NULL`` column to a table that already has rows
    explodes on PostgreSQL with ``NotNullViolationError: column "x"
    contains null values`` — because a Python-side ``default=`` only
    fires on ORM inserts, never as DDL. Autogenerate therefore emits
    ``op.add_column(sa.Column("x", ..., nullable=False))`` with no
    ``server_default``, and the database has no value to backfill the
    existing rows with.

    This hook closes that gap: for every autogenerated ``AddColumnOp``
    whose column is ``nullable=False``, carries **no** ``server_default``
    already, and **does** declare a scalar Python ``default=`` (the
    value you intended new rows to get), it copies that default into a
    ``server_default`` so the generated migration backfills existing
    rows in the same statement. The column keeps the value as its DB
    default afterwards — harmless and matching the model's intent.

    What it deliberately does **not** touch:

    * ``CreateTableOp`` columns — a brand-new table has no rows, so a
      bare ``NOT NULL`` is already safe.
    * Columns with a callable / SQL-expression default (``uuid4``,
      ``func.now()``) or no default at all — those cannot be backfilled
      deterministically and need a hand-written data migration.
    * Columns that already carry a ``server_default``.

    Compose it after :func:`reorder_base_columns_first`::

        process_revision_directives=compose_hooks(
            reorder_base_columns_first,
            backfill_non_nullable_defaults,
        )

    Args:
        context (MigrationContext): The active Alembic context — unused.
        revision (Any): The new revision identifier — unused.
        directives (list[Any]): The ``MigrationScript`` directives
            Alembic will render. Mutated in-place.
    """
    del context, revision
    try:
        from alembic.operations import ops
    except ImportError:  # pragma: no cover
        return

    import sqlalchemy as sa
    from sqlalchemy.schema import DefaultClause

    def _maybe_backfill(column: Any) -> None:
        if column.nullable:
            return
        if column.server_default is not None:
            return
        value = _column_scalar_default(column)
        if value is _MISSING:
            return
        literal = _scalar_default_literal(value)
        if literal is None:
            return
        column.server_default = DefaultClause(sa.text(literal))

    def _walk(op_list: Sequence[Any]) -> None:
        for op in op_list:
            if isinstance(op, ops.AddColumnOp):
                _maybe_backfill(op.column)
            nested: Any = getattr(op, "ops", None)
            if isinstance(nested, list):
                _walk(nested)

    for directive in directives:
        if isinstance(directive, ops.MigrationScript) and (
            directive.upgrade_ops is not None
        ):
            _walk(directive.upgrade_ops.ops)


def compose_hooks(
    *hooks: ProcessRevisionDirectives,
) -> ProcessRevisionDirectives:
    """Chain multiple ``process_revision_directives`` hooks.

    Hooks run in the order they're passed and share the same
    ``directives`` list — each can mutate it before the next sees it.

    Args:
        *hooks (ProcessRevisionDirectives): Callables matching the
            Alembic signature.

    Returns:
        ProcessRevisionDirectives: A single callable Alembic can
        register.
    """

    def _combined(
        context: MigrationContext,
        revision: Any,
        directives: list[Any],
    ) -> None:
        for hook in hooks:
            hook(context, revision, directives)

    return _combined


__all__: list[str] = [
    "BASE_COLUMN_ORDER",
    "ProcessRevisionDirectives",
    "backfill_non_nullable_defaults",
    "compose_hooks",
    "reorder_base_columns_first",
]
