"""Base SQLAlchemy ORM model with the canonical four columns."""

import re
from datetime import datetime
from typing import Any
from uuid import UUID, uuid4

from sqlalchemy import TIMESTAMP, Boolean, MetaData, Uuid, func
from sqlalchemy.ext.asyncio import AsyncAttrs
from sqlalchemy.inspection import inspect
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    declared_attr,
    mapped_column,
)

from tempest_fastapi_sdk.utils.datetime import utcnow
from tempest_fastapi_sdk.utils.dict import modify_dict

NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}
"""Alembic-friendly naming convention applied to every constraint.

Constraint names become deterministic across machines and DB engines,
so ``alembic revision --autogenerate`` only emits real schema diffs
instead of churn from auto-generated identifiers.
"""

_CAMEL_TO_SNAKE_RE = re.compile(r"(?<!^)(?=[A-Z])")


def _to_snake_case(name: str) -> str:
    """Convert ``CamelCase`` to ``snake_case``.

    Args:
        name (str): The class name to convert.

    Returns:
        str: The snake_case version.
    """
    return _CAMEL_TO_SNAKE_RE.sub("_", name).lower()


class BaseModel(AsyncAttrs, DeclarativeBase):
    """Abstract base for every SQLAlchemy model in the application.

    Every concrete model inherits the four columns required by the
    SDK conventions: ``id`` (UUID primary key, cross-DB portable),
    ``is_active`` (soft-delete flag), ``created_at`` and ``updated_at``
    (timezone-aware timestamps managed by the database).

    The class is marked ``__abstract__`` so SQLAlchemy will not try to
    map it directly. Concrete subclasses get an auto-generated
    ``__tablename__`` from their class name (e.g. ``UserModel`` →
    ``user``, ``OrderItemModel`` → ``order_item``); the ``Model``
    suffix is stripped and the remainder is snake-cased. Explicit
    ``__tablename__`` declarations still win when set.

    Equality and hashing use ``(type, id)`` so the same row loaded
    across different sessions compares equal — useful in tests and
    sets. Unflushed instances (``id is None``) fall back to Python
    identity.

    Attributes:
        metadata (MetaData): Configured with :data:`NAMING_CONVENTION`
            so Alembic generates deterministic constraint names.
        id (UUID): Primary key. Generated as UUID v4. Uses
            ``sqlalchemy.Uuid`` so the same Python type works against
            PostgreSQL, MySQL, SQLite and MSSQL.
        is_active (bool): Whether the record is active. Defaults
            to ``True``.
        created_at (datetime): Creation timestamp populated by the
            database on insert.
        updated_at (datetime): Last-update timestamp refreshed by
            the database on every update.
    """

    __abstract__ = True

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    id: Mapped[UUID] = mapped_column(
        Uuid(),
        primary_key=True,
        default=uuid4,
        doc="Primary key. UUID v4 generated by default.",
    )
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        doc="Soft-delete flag. True means the record is active.",
    )
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
        default=utcnow,
        server_default=func.now(),
        doc=(
            "Creation timestamp. Populated by Python on flush "
            "(``default=utcnow``) so the instance attribute is set "
            "immediately after ``session.flush()`` without needing "
            "a refresh. ``server_default=NOW()`` is kept as the DDL "
            "fallback for raw SQL inserts and migrations."
        ),
    )
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
        default=utcnow,
        onupdate=utcnow,
        server_default=func.now(),
        doc=(
            "Last-update timestamp. Refreshed by Python on every "
            "ORM-issued UPDATE (``onupdate=utcnow``) so the instance "
            "stays in sync without a refresh round-trip."
        ),
    )

    @declared_attr.directive
    def __tablename__(cls) -> str:  # noqa: N805
        """Derive the table name from the class name.

        Strips a trailing ``Model`` suffix and snake-cases the result.
        Concrete subclasses can still set ``__tablename__`` explicitly
        to override this default.

        Returns:
            str: The table name.
        """
        name = cls.__name__.removesuffix("Model")
        return _to_snake_case(name) if name else _to_snake_case(cls.__name__)

    def __repr__(self) -> str:
        """Render the row as ``ClassName(col=value, ...)``.

        Useful in tests and REPL exploration. Iterates over the
        mapper column attributes so it works for every subclass
        without overrides.

        Returns:
            str: A debug representation of the row.
        """
        cls = self.__class__
        column_attrs = inspect(cls).mapper.column_attrs
        columns = {attr.key: getattr(self, attr.key) for attr in column_attrs}
        columns_str = ", ".join(f"{key}={value!r}" for key, value in columns.items())
        return f"{cls.__name__}({columns_str})"

    def __eq__(self, other: object) -> bool:
        """Compare two rows by ``(type, id)``.

        Two instances of the same model class are equal when their
        primary keys match. Unflushed instances (``id is None``) fall
        back to Python identity to avoid collapsing distinct
        in-memory objects into a single bucket.

        Args:
            other (object): The right-hand operand.

        Returns:
            bool: ``True`` if both sides represent the same row.
        """
        if not isinstance(other, self.__class__):
            return NotImplemented
        if self.id is None or other.id is None:
            return self is other  # type: ignore[unreachable]
        return bool(self.id == other.id)

    def __hash__(self) -> int:
        """Return a hash compatible with :meth:`__eq__`.

        Hashes flushed rows by ``(class name, id)`` so equal rows
        share a bucket. Unflushed rows fall back to ``id(self)`` so
        distinct in-memory objects don't collide in sets/dicts
        before they have a primary key.

        Returns:
            int: The hash value.
        """
        if self.id is None:
            return object.__hash__(self)  # type: ignore[unreachable]
        return hash((type(self).__name__, self.id))

    def to_dict(
        self,
        exclude: list[str] | None = None,
        include: dict[str, Any] | None = None,
        remove_none: bool = False,
    ) -> dict[str, Any]:
        """Serialize the row to a plain ``dict``.

        Args:
            exclude (list[str] | None): Column names to drop from
                the output.
            include (dict[str, Any] | None): Extra entries to merge
                into the output.
            remove_none (bool): Whether to strip keys whose value
                is ``None``.

        Returns:
            dict[str, Any]: The serialized representation.
        """
        column_attrs = inspect(self.__class__).mapper.column_attrs
        data: dict[str, Any] = {
            attr.key: getattr(self, attr.key) for attr in column_attrs
        }
        if remove_none:
            data = {key: value for key, value in data.items() if value is not None}
        return modify_dict(data, exclude=exclude, include=include)

    def update_from_dict(
        self,
        data: dict[str, Any],
        allowed_fields: set[str] | None = None,
    ) -> None:
        """Bulk-assign attributes from a dict.

        Unknown keys are silently ignored — only mapped columns of
        ``self.__class__`` are eligible. When ``allowed_fields`` is
        provided, only the intersection with model columns is
        applied; this is the recommended way to consume external
        payloads (e.g. PATCH bodies) so callers can't write to
        sensitive columns like ``id`` or ``role`` by mistake.

        Args:
            data (dict[str, Any]): The payload (typically
                ``schema.to_dict()``).
            allowed_fields (set[str] | None): Whitelist of column
                names; only these keys are applied. ``None`` accepts
                every mapped column (use only for trusted payloads).
        """
        columns = {c.key for c in inspect(self.__class__).mapper.column_attrs}
        keys = (allowed_fields & columns) if allowed_fields is not None else columns
        for key, value in data.items():
            if key in keys:
                setattr(self, key, value)


__all__: list[str] = [
    "NAMING_CONVENTION",
    "BaseModel",
]
